"use client";
import {useEffect,useState} from "react";
import {ArrowUpRight,Check,Copy,Link2,Loader2,RefreshCw,ShieldCheck,Unplug,Zap} from "lucide-react";
import {toast} from "sonner";
type Connection={id:string;name:string;scopes:string;created_at:number;last_used_at:number;refresh_expires:number};
type Data={url:string;connections:Connection[];activity:Array<{tool:string;state:string;created_at:number}>};
const labels:Record<string,string>={"products:read":"Read workspace","products:write":"Edit products","ai:generate":"Paid AI generation","products:publish":"Publish products"};
export function ConnectionsPanel({signedIn}:{signedIn:boolean}){
  const [data,setData]=useState<Data|null>(null),[client,setClient]=useState<"Claude"|"ChatGPT">("Claude"),[busy,setBusy]=useState(""),[error,setError]=useState(""),[copied,setCopied]=useState(false);
  async function load(){if(!signedIn)return;setError("");try{const r=await fetch("/api/connections"),d=await r.json() as Data&{error:string};if(!r.ok)throw new Error(d.error);setData(d);}catch(e){setError((e as Error).message);}}
  useEffect(()=>{void load();},[signedIn]);
  async function disconnect(id:string){setBusy(id);try{const r=await fetch("/api/connections",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});if(!r.ok)throw new Error("Could not disconnect. Try again.");await load();toast.success("Connection revoked. The assistant can no longer access FiveGen.");}catch(e){setError((e as Error).message);}finally{setBusy("");}}
  async function copy(text:string){try{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1800);}catch{toast.error("Copy unavailable. Select and copy the address below.");}}
  const url=data?.url||"https://www.fivegen.ai/api/mcp";
  return <div className="connections-layout">
    {error&&<p className="error-banner" role="alert">{error}</p>}
    <section className="panel connection-setup"><div className="connection-heading"><div className="connection-mark"><Link2 size={24}/></div><div><span className="eyebrow">YOUR STUDIO, IN THE CONVERSATION</span><h2>Connect your AI assistant.</h2><p>Create private products, refine content and generate visuals from Claude or ChatGPT.</p></div></div>
      <div className="connection-tabs" role="tablist" aria-label="Choose AI assistant">{(["Claude","ChatGPT"] as const).map(name=><button key={name} role="tab" aria-selected={client===name} onClick={()=>setClient(name)}>{name}<ArrowUpRight size={15}/></button>)}</div>
      <div className="connection-address"><label htmlFor="mcp-url">FiveGen MCP server URL</label><div><input id="mcp-url" value={url} readOnly onFocus={e=>e.target.select()}/><button className="button secondary" onClick={()=>void copy(url)}>{copied?<Check size={16}/>:<Copy size={16}/>}<span>{copied?"Copied":"Copy URL"}</span></button></div></div>
      <ol className="connection-steps"><li><b>1</b><span><strong>{client==="Claude"?"Open Customize → Connectors":"Open Settings → Security and login"}</strong><small>{client==="Claude"?"Choose Add custom connector and name it FiveGen.":"Enable developer mode if available, then open ChatGPT Plugins and add a connection named FiveGen."}</small></span></li><li><b>2</b><span><strong>Paste the server URL</strong><small>Use OAuth authentication. FiveGen supports automatic client registration; no provider API key is needed.</small></span></li><li><b>3</b><span><strong>Sign in and choose permissions</strong><small>Connect the same FiveGen account. Paid AI generation is an optional permission you explicitly enable.</small></span></li></ol>
      {!signedIn&&<a className="button primary" href="/signin-with-chatgpt?return_to=/%3Fconnect%3Dmcp">Sign in to connect <ArrowUpRight size={16}/></a>}
      <div className="connection-note"><ShieldCheck size={18}/><p>Sign in to authorize your assistant and choose what it can do. Your workspace data requires permission, and master API keys stay private. You can revoke access anytime below.</p></div>
      <a className="text-link" href={client==="Claude"?"https://support.claude.com/en/articles/11175166-get-started-with-custom-connectors-using-remote-mcp":"https://developers.openai.com/apps-sdk/deploy/connect-chatgpt"} target="_blank" rel="noreferrer">{client} setup guide <ArrowUpRight size={14}/></a>
    </section>
    <aside className="connection-side"><section className="panel"><div className="panel-heading"><h2>Connected assistants</h2><button className="icon-button" aria-label="Refresh connections" onClick={()=>void load()}><RefreshCw size={16}/></button></div>{data?.connections.length?data.connections.map(c=><div className="connected-assistant" key={c.id}><div><strong>{c.name}</strong><small>{c.refresh_expires<Date.now()?"Expired · reconnect to continue":`Last used ${new Date(c.last_used_at).toLocaleDateString()}`}</small></div><div className="connection-scopes">{c.scopes.split(" ").filter(s=>s!=="products:publish").map(s=><span key={s}>{labels[s]||s}</span>)}</div><button className="text-link" disabled={!!busy} onClick={()=>void disconnect(c.id)}>{busy===c.id?<Loader2 className="spin" size={14}/>:<Unplug size={14}/>}Disconnect</button></div>):<div className="connection-empty"><Link2 size={27}/><strong>{signedIn?"Your next connection starts here.":"Sign in to manage connections."}</strong><p>After authorization, your assistant and its permissions appear here.</p></div>}</section>
      <section className="panel connection-cost"><Zap size={22}/><h3>Same studio. Same limits.</h3><p>Content written by your connected assistant uses no FiveGen AI credits. FiveGen generation uses your existing balance.</p><div><span>Marketing image</span><strong>12 credits</strong></div><div><span>5s video + audio</span><strong>160 credits</strong></div><small>Manual products are unlimited. Three FiveGen AI products are included each month; further AI generation uses credits. No automatic credit purchases.</small></section>
    </aside>
    <section className="panel connection-prompt"><div><span className="eyebrow">TRY YOUR FIRST PRODUCT</span><h3>Start with an idea. Finish with something worth selling.</h3><p>“Create a practical first-client playbook for freelance designers. Write the chapters, add a pricing calculator and prepare the launch campaign. Save it as a draft in FiveGen for my review.”</p></div><button className="button secondary" onClick={()=>void copy("Create a practical first-client playbook for freelance designers. Write the chapters, add a pricing calculator and prepare the launch campaign. Save it as a draft in FiveGen for my review.")}><Copy size={15}/>Copy prompt</button></section>
    {!!data?.activity.length&&<section className="panel connection-activity"><h2>Recent assistant activity</h2>{data.activity.map((a,i)=><div key={i}><span>{a.tool.replaceAll("_"," ")}</span><span className={a.state==="failed"?"activity-failed":""}>{a.state}</span><time>{new Date(a.created_at).toLocaleString()}</time></div>)}</section>}
  </div>;
}
