"use client";
import {useEffect,useState} from 'react';
import {ArrowUpRight,Check,Coins,Film,ImagePlus,Loader2,RefreshCw,Sparkles} from 'lucide-react';
import {creditPacks,type CreditBalance} from '@/lib/credit-policy';
import {money} from '@/lib/product';
import {toast} from 'sonner';
type CreditData={balance:CreditBalance;billingReady:boolean;costs:{text:number;image:number;video:number};history:Array<{operation:string;cost:number;state:string;created_at:number}>};
export function CreditsPanel({signedIn}:{signedIn:boolean}){
 const [data,setData]=useState<CreditData|null>(null),[busy,setBusy]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[legacy,setLegacy]=useState(false),[notice,setNotice]=useState('');
 async function load(){if(!signedIn)return;setLoading(true);setError('');try{const q=new URLSearchParams(location.search),session=q.get('billing')==='credits'?q.get('session_id'):null;const r=await fetch(`/api/credits${session?`?session_id=${encodeURIComponent(session)}`:''}`),d=await r.json() as any;if(!r.ok)throw new Error(d.error);setData(d);if(session){history.replaceState(null,'','/?billing=credits');setNotice('Payment confirmed. Your credits are ready.');}const b=await fetch('/api/billing');if(b.ok){const p=await b.json() as any;setLegacy(p.hasCustomer&&!p.cancelAtPeriodEnd&&['active','trialing','past_due','unpaid'].includes(p.status));}}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[signedIn]);
 async function buy(pack:string){if(!signedIn){location.assign('/signin-with-chatgpt?return_to=/?billing=credits');return;}setBusy(pack);setError('');try{const r=await fetch('/api/credits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pack})}),d=await r.json() as any;if(!r.ok)throw new Error(d.error);location.assign(d.url);}catch(e){setError((e as Error).message);toast.error((e as Error).message);setBusy('');}}
 const allowance=data?.balance.products;
 return <div className="credit-workspace"><section className="credit-hero"><div><span className="eyebrow">ALL THE TOOLS. YOUR OWN PACE.</span><h2>More room to create.</h2><p>Every workspace feature is included. Three AI products each month are on us. Top up when you need more.</p><div className="credit-inclusions">{['Unlimited manual products','Funnels & deals','Courses & communities'].map(t=><span key={t}><Check size={13}/>{t}</span>)}</div></div><span className="credit-orbit"><Sparkles size={35}/></span></section>
 {error&&<div role="alert" className="error-banner">{error}<button className="text-link" disabled={loading} onClick={()=>void load()}>Try again</button></div>}{notice&&<p role="status" className="credit-success"><Check size={17}/>{notice}</p>}
 <div className="credit-overview"><section className="credit-stat"><div className="credit-stat-label"><span>Monthly AI products</span><Sparkles size={18}/></div><strong>{allowance?allowance.remaining:signedIn?'—':3}<small> / 3 remaining</small></strong><div className="allowance-dots" aria-hidden="true">{[0,1,2].map(i=><span key={i} className={i<(allowance?.remaining??3)?'available':''}/>)}</div><p>{allowance?`Resets ${new Date(allowance.resetsAt).toLocaleDateString(undefined,{month:'long',day:'numeric',timeZone:'UTC'})} · UTC`:'A fresh allowance every calendar month.'}</p></section><section className="credit-stat"><div className="credit-stat-label"><span>Your credit balance</span><button className="icon-button" aria-label="Refresh credit balance" disabled={!signedIn||loading} onClick={()=>void load()}><RefreshCw size={16} className={loading?'spin':''}/></button></div><strong>{data?data.balance.purchased.toLocaleString():'—'}<small> credits</small></strong><p>One balance for extra products, images, and videos. Purchased credits never expire.</p><a className="text-link" href="#credit-packs">Top up your balance <ArrowUpRight size={14}/></a></section></div>
 <section className="credit-costs"><div className="credit-section-heading"><h3>Know the cost before you create.</h3><span>No automatic top-ups</span></div><div className="credit-rate-cards">{[[Sparkles,'Product content',`${data?.costs.text??10} credits / step`,'After your 3 included runs. Individual rewrites also use credits.'],[ImagePlus,'Marketing image',`${data?.costs.image??12} credits`,'Create a campaign visual in your chosen aspect ratio.'],[Film,'Marketing video',`${data?.costs.video??160} credits`,'A 5-second video with audio. Always uses credits.']].map(([Icon,title,price,copy])=>{const I=Icon as typeof Sparkles;return <article key={String(title)}><I size={21}/><h4>{String(title)}</h4><strong>{String(price)}</strong><p>{String(copy)}</p></article>;})}</div><p className="field-help">Included runs cover the outline, content, files, and launch kit. Most products take 5–12 steps; longer products can use up to 32. Paid steps are saved as they finish. Confirmed failed generations return credits.</p></section>
 <section id="credit-packs"><div className="credit-section-heading"><div><h3>A little fuel. A lot of possibility.</h3><p>One-time credit packs · USD · secure Stripe checkout</p></div></div><div className="credit-pack-grid">{creditPacks.map((p,i)=><article className={`credit-pack ${i===1?'featured':''}`} key={p.id}>{i===1&&<span className="credit-pack-tag">CREATOR PACK</span>}<Coins size={22}/><h4>{['A fresh start','Keep creating','Build at scale'][i]}</h4><strong>{p.credits.toLocaleString()} <small>credits</small></strong><div className="credit-pack-price">{money(p.cents)}<small>one time</small></div><p>{(p.cents/p.credits).toFixed(2)}¢ per credit · no expiry</p><button className={`button ${i===1?'primary':'secondary'} full`} disabled={!!busy||(signedIn&&(!data?.billingReady||loading))} onClick={()=>void buy(p.id)}>{busy===p.id?<Loader2 className="spin" size={17}/>:<ArrowUpRight size={17}/>} {busy===p.id?'Opening checkout…':`Buy ${p.credits.toLocaleString()} credits`}</button></article>)}</div>{signedIn&&data&&!data.billingReady&&<p className="field-help">Credit checkout is being configured. You can keep building manual products and use your included AI runs when AI is available.</p>}</section>
 {legacy&&<section className="legacy-billing"><div><h3>Your previous subscription</h3><p>Plans have been retired. Stop renewal and keep every workspace feature.</p></div><button className="button secondary" disabled={!!busy} onClick={async()=>{setBusy('cancel');setError('');try{const r=await fetch('/api/billing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'cancel'})});if(!r.ok)throw new Error(((await r.json()) as any).error);setLegacy(false);setNotice('Your previous plan will not renew. All tools remain available.');}catch(e){setError((e as Error).message);}finally{setBusy('');}}}>Stop subscription renewal</button></section>}
 {!!data?.history.length&&<details className="credit-history panel"><summary>Recent credit activity</summary>{data.history.map((h,i)=><div key={i}><span>{h.operation==='text'?'Product content':h.operation==='image'?'Marketing image':'Marketing video'}<small>{new Date(h.created_at).toLocaleString()}</small></span><span>{h.state==='refunded'?'Returned':h.state==='reserved'?'Reserved':'Used'} {h.cost} credits</span></div>)}</details>}<p className="credit-terms"><a href="/terms#ai-credits" target="_blank" rel="noreferrer">Credit and selling terms</a> · No FiveGen subscription required.</p>
 </div>;
}
