'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,Check,Coins,Film,ImagePlus,RefreshCw,Sparkles} from 'lucide-react';
import type {CreditBalance} from '@/lib/credit-policy';
type CreditData={balance:CreditBalance;costs:{text:number;image:number;video:number};history:Array<{operation:string;cost:number;state:string;created_at:number}>};
export function CreditsPanel({signedIn}:{signedIn:boolean}){
 const [data,setData]=useState<CreditData|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[legacy,setLegacy]=useState(false),[canceling,setCanceling]=useState(false);
 async function load(){if(!signedIn)return;setLoading(true);setError('');try{const r=await fetch('/api/credits'),d=await r.json() as CreditData&{error:string};if(!r.ok)throw new Error(d.error);setData(d);const old=await fetch('/api/billing');if(old.ok){const b=await old.json() as any;setLegacy(b.hasCustomer&&!b.cancelAtPeriodEnd&&['active','trialing','past_due','unpaid'].includes(b.status));}}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[signedIn]);
 if(data?.balance.unlimited)return <div className="credit-workspace"><section className="credit-hero"><div><span className="eyebrow">YOUR ACCOUNT ACCESS</span><h2>Create without limits.</h2><p>Unlimited AI planning, products, rewrites, images, and videos are enabled for your account. No credit purchases or subscription are required.</p><div className="credit-inclusions">{['Unlimited products','Unlimited images & video','No credit deductions'].map(t=><span key={t}><Check size={13}/>{t}</span>)}</div></div><span className="credit-orbit"><Sparkles size={35}/></span></section><section className="credit-stat"><div className="credit-stat-label"><span>Generation access</span><button className="icon-button" disabled={loading} aria-label="Refresh generation access" onClick={()=>void load()}><RefreshCw size={16} className={loading?'spin':''}/></button></div><strong>Unlimited</strong><p>Provider charges still apply to the platform. Service availability and concurrent job limits remain in place.</p><a className="text-link" href="/">Back to your studio <ArrowRight size={14}/></a></section><p className="credit-terms">Existing purchased credits and subscriptions are unchanged. <a href="/account/billing">Manage billing</a></p>{error&&<div className="error-banner" role="alert">{error}</div>}</div>;
 return <div className="credit-workspace"><section className="credit-hero"><div><span className="eyebrow">A LITTLE FUEL. A LOT OF POSSIBILITY.</span><h2>Stay in your creative flow.</h2><p>A monthly allowance for your next ideas. Credits when you want to go further.</p><div className="credit-inclusions">{['Private products','Editable files & downloads','Original images & video'].map(t=><span key={t}><Check size={13}/>{t}</span>)}</div></div><span className="credit-orbit"><Sparkles size={35}/></span></section>
 {error&&<div className="error-banner" role="alert">{error}<button className="text-link" disabled={loading} onClick={()=>void load()}>Retry</button></div>}
 <div className="credit-overview"><section className="credit-stat"><div className="credit-stat-label"><span>Free AI products this month</span><Sparkles size={18}/></div><strong>{data?.balance.products.remaining??(signedIn?'—':3)}<small> / 3 remaining</small></strong><div className="allowance-dots" aria-hidden="true">{[0,1,2].map(i=><span key={i} className={i<(data?.balance.products.remaining??3)?'available':''}/>)}</div><p>Includes the outline, finished sections, supporting files and launch copy. Resets each UTC calendar month.</p></section><section className="credit-stat"><div className="credit-stat-label"><span>Available AI credits</span><button className="icon-button" disabled={!signedIn||loading} aria-label="Refresh credit balance" onClick={()=>void load()}><RefreshCw size={16} className={loading?'spin':''}/></button></div><strong>{data?data.balance.total.toLocaleString():'—'}<small> credits</small></strong><p>{data?`${data.balance.included.toLocaleString()} subscription · ${data.balance.purchased.toLocaleString()} purchased`:'One balance for content, images, and video.'}</p>{data?.balance.renewsAt&&<p>Subscription credits reset {new Date(data.balance.renewsAt).toLocaleDateString()}. Purchased credits never expire.</p>}<a className="text-link" href="/pricing?type=packs">Add more credits <ArrowRight size={14}/></a></section></div>
 <section className="credit-costs"><div className="credit-section-heading"><h3>Know the cost before you create.</h3><span>No automatic top-ups</span></div><div className="credit-rate-cards">{[[Sparkles,'Product content',`${data?.costs.text??10} credits / step`,'Your first 3 complete products are included each month. Further products and rewrites use credits.'],[ImagePlus,'Product image',`${data?.costs.image??12} credits`,'An original visual, art-directed for your product.'],[Film,'Product video',`${data?.costs.video??160} credits`,'A 5-second video with audio.']].map(([Icon,title,cost,copy])=>{const I=Icon as typeof Sparkles;return <article key={String(title)}><I size={21}/><h4>{String(title)}</h4><strong>{String(cost)}</strong><p>{String(copy)}</p></article>;})}</div><p className="field-help">20 AI planning messages are included each month; additional messages use the current text-step rate. Product generation usually takes 5–12 steps, or up to 32 for longer formats. Failed generations return reserved credits. Images and videos always use credits.</p></section>
 <section className="gen-editor-next"><Coins size={24}/><div><strong>Choose your pace.</strong><p>Subscribe for credits every month, or buy a one-time pack. All creation tools are available on every account.</p></div><a className="button primary" href="/pricing">Plans & credit packs <ArrowRight size={15}/></a><a className="button secondary" href="/account/billing">Manage billing</a></section>
 {legacy&&<section className="legacy-billing"><div><h3>Previous Stripe subscription</h3><p>Manage a subscription from the previous billing system.</p></div><button className="button secondary" disabled={canceling} onClick={async()=>{setCanceling(true);try{const r=await fetch('/api/billing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'cancel'})});if(!r.ok)throw new Error(((await r.json()) as any).error);setLegacy(false);}catch(e){setError((e as Error).message);}finally{setCanceling(false);}}}>Stop renewal</button></section>}
 {!!data?.history.length&&<details className="credit-history panel"><summary>Recent credit activity</summary>{data.history.map((h,i)=><div key={i}><span>{{text:'Product content',planning:'AI planning',image:'Product image',video:'Product video'}[h.operation]||h.operation}<small>{new Date(h.created_at).toLocaleString()}</small></span><span>{h.state==='refunded'?'Returned':h.state==='reserved'?'Reserved':'Used'} {h.cost} credits</span></div>)}</details>}<p className="credit-terms">Subscription credits are used first and do not roll over. Purchased credits never expire. <a href="/terms#ai-credits">Credit terms</a></p>
 </div>;
}
