"use client";
import {useEffect,useState} from 'react';
import {CalendarDays,Download,Loader2,Search,Users,TrendingUp,ShoppingBag} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {journeyApi} from './delivery-panel';
import {money} from '@/lib/product';
function csvCell(value:unknown){const s=String(value??'');return '"'+(/^[=+@-]/.test(s)?"'"+s:s).replaceAll('"','""')+'"';}
export function CRMPanel(){const [data,setData]=useState<any>(null),[tab,setTab]=useState('leads'),[days,setDays]=useState('30'),[search,setSearch]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const load=()=>journeyApi(`/api/crm?days=${days}`).then(setData);useEffect(()=>{setData(null);void load().catch(e=>setError(e.message));},[days]);
 const rows=(data?.[tab]||[]).filter((r:any)=>`${r.name||''} ${r.email} ${r.title} ${r.status||''}`.toLowerCase().includes(search.toLowerCase()));const c=data?.counts||{},bookingRate=c.leads?Math.round(c.booked_leads/c.leads*100):null,showRate=Number(c.attended)+Number(c.no_shows)?Math.round(c.attended/(Number(c.attended)+Number(c.no_shows))*100):null;
 function download(){const cols=tab==='leads'?['name','email','title','source','marketing','purchases']:tab==='bookings'?['name','email','title','starts_at','status','notes']:['email','title','amount','platform_fee','referral_fee','created_at'];const csv=[cols.join(','),...rows.map((r:any)=>cols.map(k=>csvCell(k.endsWith('_at')?new Date(r[k]).toISOString():r[k])).join(','))].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download=`fivegen-${tab}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="crm-panel"><div className="journey-heading"><Select value={days} onValueChange={setDays}><SelectTrigger aria-label="CRM reporting period"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="30">Last 30 days</SelectItem><SelectItem value="90">Last 90 days</SelectItem><SelectItem value="365">Last year</SelectItem></SelectContent></Select></div><div className="journey-metrics">{[[Users,'Captured leads',c.leads??'—','Unique email per product'],[CalendarDays,'Booking rate',bookingRate===null?'—':`${bookingRate}%`,'Captured leads with a non-cancelled booking'],[TrendingUp,'Show-up rate',showRate===null?'—':`${showRate}%`,'Attended ÷ attended + no-show'],[ShoppingBag,'Gross sales',data?money(Number(c.revenue||0)):'—',`${c.sales||0} paid orders · before fees & refunds`]].map(([Icon,label,value,note]:any)=><div className="journey-metric" key={label}><Icon size={20}/><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</div>
 <div className="crm-toolbar"><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="leads">Leads</TabsTrigger><TabsTrigger value="bookings">Bookings</TabsTrigger><TabsTrigger value="sales">Sales</TabsTrigger></TabsList></Tabs><label className="journey-search"><Search size={16}/><input aria-label="Search CRM" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, email, product…"/></label><button className="button secondary" disabled={!rows.length} onClick={download}><Download size={16}/>Export CSV</button></div>{error&&<p className="error-banner" role="alert">{error}</p>}
 <section className="panel crm-table">{!data?<div className="quiet-empty"><Loader2 className="spin" size={24}/>Loading your CRM…</div>:rows.length?<Table><TableHeader><TableRow><TableHead>Contact</TableHead><TableHead>Product</TableHead><TableHead>{tab==='leads'?'Source':tab==='bookings'?'Meeting time':'Gross amount'}</TableHead><TableHead>{tab==='leads'?'Relationship':tab==='bookings'?'Attendance':'Fees & share'}</TableHead><TableHead>{tab==='leads'?'Email permission':'Details'}</TableHead></TableRow></TableHeader><TableBody>{rows.map((r:any)=><TableRow key={r.id}><TableCell><strong>{r.name||r.email}</strong>{r.name&&<small>{r.email}</small>}</TableCell><TableCell>{r.title}</TableCell><TableCell>{tab==='leads'?r.source:tab==='bookings'?<>{new Date(r.starts_at).toLocaleString()}<small>{r.duration} minutes</small></>:money(r.amount)}</TableCell><TableCell>{tab==='leads'?<span className="journey-badge">{r.purchases?'Customer':'Lead'}</span>:tab==='bookings'?<Select value={r.status} disabled={busy===r.id||r.status==='cancelled'} onValueChange={async status=>{setBusy(r.id);setError('');try{await journeyApi('/api/crm','PATCH',{id:r.id,status});await load();}catch(e){setError((e as Error).message);}finally{setBusy('');}}}><SelectTrigger aria-label={`Attendance for ${r.name}`}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="confirmed">Scheduled</SelectItem><SelectItem value="attended" disabled={r.starts_at>Date.now()}>Attended</SelectItem><SelectItem value="no_show" disabled={r.starts_at>Date.now()}>No-show</SelectItem><SelectItem value="cancelled">Cancelled</SelectItem></SelectContent></Select>:<>{money(r.platform_fee)} platform<small>{money(r.referral_fee)} referral</small></>}</TableCell><TableCell>{tab==='leads'?(r.marketing?'Opted in':'Transactional only'):tab==='bookings'?<details><summary>Preparation notes</summary><p>{r.notes||'No notes supplied.'}</p></details>:new Date(r.created_at).toLocaleDateString()}</TableCell></TableRow>)}</TableBody></Table>:<div className="quiet-empty"><Users size={30}/><h3>{search?'No matching contacts yet.':tab==='leads'?'Your next customer starts with a conversation.':tab==='bookings'?'Your calendar is ready for its first booking.':'Your sales will appear here.'}</h3><p>{tab==='leads'?'Publish a free guide funnel or share your product to capture real leads.':tab==='bookings'?'Enable bookings in a product’s Delivery tab, then add available times.':'Paid checkouts are recorded automatically.'}</p></div>}</section><p className="field-help">{tab==='bookings'?'Mark completed meetings as Attended or No-show. Future and unmarked meetings are excluded from show-up rate. Times use your device timezone.':'Booking rate follows leads captured in this period. Sales and bookings use their own dates.'} Tables show up to 1,000 records; headline metrics include the entire selected period.</p></div>;
}
