"use client";
import {useEffect,useState} from 'react';
import {CalendarDays,Check,Film,Loader2,Plus,Trash2,Upload,Users,ArrowUpRight,FileText} from 'lucide-react';
import {toast} from 'sonner';
import {Switch} from '@/components/ui/switch';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {type Product} from '@/lib/product';
import {readExperience,uploadLimit} from '@/lib/experience';
export type UploadedFile={id:string;name:string;mime:string;size:number};
export async function journeyApi<T=any>(url:string,method='GET',body?:unknown):Promise<T>{const r=await fetch(url,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json() as any;if(!r.ok)throw new Error(d.error||'Please try again.');return d;}
export function UploadButton({productId,onUpload,videoOnly=false}:{productId:string;onUpload:(f:UploadedFile)=>void;videoOnly?:boolean}){
 const [progress,setProgress]=useState<number|null>(null),[error,setError]=useState('');
 return <div className="upload-control"><label className={`button secondary ${progress!==null?'is-uploading':''}`}><Upload size={16}/>{progress===null?(videoOnly?'Upload video class':'Upload file'):`Uploading ${progress}%`}<input type="file" disabled={progress!==null} accept={videoOnly?'video/mp4,video/webm':'video/mp4,video/webm,application/pdf,image/png,image/jpeg,image/webp,text/plain,text/csv'} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setError('');if(file.size>uploadLimit){setError('This file exceeds 100 MB. Split long recordings into separate lessons.');return;}setProgress(0);const xhr=new XMLHttpRequest();xhr.open('POST',`/api/products/${productId}/uploads?name=${encodeURIComponent(file.name)}`);xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');xhr.setRequestHeader('X-File-Size',String(file.size));xhr.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(e.loaded/e.total*100));};xhr.onload=()=>{setProgress(null);try{const d=JSON.parse(xhr.responseText);if(xhr.status>=400)throw new Error(d.error);onUpload(d.upload);toast.success('Upload ready. Save the product to attach it.');}catch(e){setError((e as Error).message);}};xhr.onerror=()=>{setProgress(null);setError('Upload interrupted. Your other files are safe; please retry.');};xhr.send(file);}}/></label>{progress!==null&&<progress max={100} value={progress} aria-label="Upload progress"/>}{error&&<p role="alert" className="error-banner">{error}</p>}</div>;
}
export function DeliveryPanel({product,onChange,pro,onUpgrade,onSave}:{product:Product;onChange:(p:Product)=>void;pro:boolean;onUpgrade:()=>void;onSave:()=>Promise<boolean>}){
 const [files,setFiles]=useState<UploadedFile[]>([]),[slots,setSlots]=useState<any[]>([]),[date,setDate]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const exp=readExperience(product.experience),zone=Intl.DateTimeFormat().resolvedOptions().timeZone;
 const load=()=>Promise.all([journeyApi(`/api/products/${product.id}/uploads`),journeyApi(`/api/products/${product.id}/slots`)]).then(([a,b])=>{setFiles(a.uploads);setSlots(b.slots);}).catch(e=>setError(e.message));
 useEffect(()=>{void load();},[product.id]);
 const update=(v:Partial<typeof exp>)=>onChange({...product,experience:{...exp,...v}});
 const addFile=(f:UploadedFile)=>setFiles(v=>[f,...v]);
 return <div className="journey-surface"><div className="journey-heading"><div><h2>Your customer’s member space</h2><p>Set up classes, resources, and the support that comes with your product.</p></div><a className="button secondary" href={`/learn/${product.slug}`} target="_blank" rel="noreferrer">Preview member space <ArrowUpRight size={16}/></a></div>
 {!pro&&<div className="journey-notice"><div><strong>Build a richer product with Pro</strong><p>Video uploads, bookings, private communities, funnels, and referral partners. Your existing downloads remain available on Free.</p></div><button className="button primary" onClick={onUpgrade}>Explore Pro</button></div>}
 <div className="delivery-grid"><section className="panel journey-card"><div className="journey-card-title"><Film size={22}/><div><h3>Video classroom</h3><p>Attach a class to any lesson. Students can return and track their progress.</p></div></div>
 <fieldset disabled={!pro}><div className="lesson-upload-list">{product.content.sections.map((s,i)=><div className="lesson-upload-row" key={s.id||i}><span className="lesson-number">{String(i+1).padStart(2,'0')}</span><div><strong>{s.title}</strong><Select value={s.videoId||'none'} onValueChange={v=>onChange({...product,content:{...product.content,sections:product.content.sections.map((x,j)=>j===i?{...x,id:x.id||crypto.randomUUID(),videoId:v==='none'?undefined:v}:x)}})}><SelectTrigger aria-label={`Video for ${s.title}`}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Text lesson · no video</SelectItem>{files.filter(f=>f.mime.startsWith('video/')).map(f=><SelectItem key={f.id} value={f.id}>{f.name}</SelectItem>)}</SelectContent></Select></div>{s.videoId&&<a className="icon-button" title="Play uploaded video" href={`/api/uploads/${s.videoId}`} target="_blank" rel="noreferrer"><Film size={18}/></a>}</div>)}</div><UploadButton productId={product.id} videoOnly onUpload={addFile}/></fieldset><small>MP4 or WebM · 100 MB per file · 2 GB per Pro workspace. Uploads are private unless attached to a published sales video.</small></section>
 <section className="panel journey-card"><div className="journey-card-title"><Users size={22}/><div><h3>Private community</h3><p>Give customers a place to ask questions, share progress, and help each other.</p></div><Switch aria-label="Enable private community" disabled={!pro} checked={exp.community.enabled} onCheckedChange={enabled=>update({community:{...exp.community,enabled}})}/></div>{exp.community.enabled?<div className="form-stack"><label>Welcome message<textarea rows={3} value={exp.community.welcome} maxLength={4000} onChange={e=>update({community:{...exp.community,welcome:e.target.value}})} placeholder="Introduce the space and suggest a useful first post."/></label><label>Community guidelines<textarea rows={3} maxLength={4000} value={exp.community.rules} onChange={e=>update({community:{...exp.community,rules:e.target.value}})}/></label><p className="field-help">Only customers and you can participate. You can pin discussions and remove posts. </p></div>:<div className="quiet-empty"><Users size={28}/><p>Turn customers into a community, one useful conversation at a time.</p></div>}</section>
 <section className="panel journey-card"><div className="journey-card-title"><CalendarDays size={22}/><div><h3>Meetings & bookings</h3><p>Each paid purchase includes one session; free access includes one introductory session.</p></div><Switch aria-label="Enable bookings" disabled={!pro} checked={exp.booking.enabled} onCheckedChange={enabled=>update({booking:{...exp.booking,enabled,timezone:zone}})}/></div>{exp.booking.enabled&&<div className="form-stack"><div className="form-two"><label>Session length · minutes<input type="number" min={15} max={180} value={exp.booking.duration} onChange={e=>update({booking:{...exp.booking,duration:Number(e.target.value)}})}/></label><label>Meeting link<input type="url" placeholder="https://meet.google.com/…" value={exp.booking.meetingUrl} onChange={e=>update({booking:{...exp.booking,meetingUrl:e.target.value}})}/></label></div><label>What should customers prepare?<textarea rows={3} value={exp.booking.preparation} maxLength={4000} onChange={e=>update({booking:{...exp.booking,preparation:e.target.value}})}/></label><div className="slot-composer"><label>Available time · {zone}<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="button secondary" disabled={busy||!date} onClick={async()=>{setBusy(true);setError('');try{if(!await onSave())return;await journeyApi(`/api/products/${product.id}/slots`,'POST',{startsAt:new Date(date).getTime()});setDate('');await load();toast.success('Booking time added');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Plus size={16}/>Add time</button></div><div className="slot-list">{slots.filter(s=>s.starts_at>Date.now()).map(s=><div key={s.id}><span>{new Date(s.starts_at).toLocaleString()} <small>{s.duration} min · {s.booking_id?'Booked':'Available'}</small></span><button className="icon-button" disabled={!!s.booking_id} aria-label={`Remove slot ${new Date(s.starts_at).toLocaleString()}`} onClick={async()=>{try{await journeyApi(`/api/products/${product.id}/slots`,'DELETE',{slotId:s.id});await load();}catch(e){setError((e as Error).message);}}}><Trash2 size={15}/></button></div>)}</div><small>Each time is reserved for one customer. Overlapping bookings are blocked across your products. Manage attendance in CRM.</small></div>}</section>
 {exp.booking.enabled&&<section className="panel journey-card"><div className="journey-card-title"><Check size={22}/><div><h3>After the booking</h3><p>Replace a dead-end confirmation with a useful next step.</p></div></div><fieldset disabled={!pro}><div className="form-stack"><label>Confirmation heading<input value={exp.booking.confirmationTitle} maxLength={150} onChange={e=>update({booking:{...exp.booking,confirmationTitle:e.target.value}})}/></label><label>Confirmation message<textarea rows={4} maxLength={6000} value={exp.booking.confirmationBody} onChange={e=>update({booking:{...exp.booking,confirmationBody:e.target.value}})} placeholder="Explain what happens next, what to bring, and how to get the most from the session."/></label><label>Welcome or preparation video<Select value={exp.booking.confirmationVideoId||'none'} onValueChange={v=>update({booking:{...exp.booking,confirmationVideoId:v==='none'?undefined:v}})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">No video</SelectItem>{files.filter(f=>f.mime.startsWith('video/')).map(f=><SelectItem key={f.id} value={f.id}>{f.name}</SelectItem>)}</SelectContent></Select></label></div></fieldset></section>}
 <section className="panel journey-card delivery-resources"><div className="journey-card-title"><FileText size={22}/><div><h3>Supporting uploads</h3><p>PDF workbooks, images, and resources appear in the customer’s member space.</p></div></div><fieldset disabled={!pro}><UploadButton productId={product.id} onUpload={addFile}/></fieldset><div className="resource-list">{files.map(f=><div key={f.id}><a href={`/api/uploads/${f.id}?download=1`}>{f.name}</a><small>{(f.size/1024/1024).toFixed(1)} MB</small><button className="icon-button" aria-label={`Remove ${f.name}`} onClick={async()=>{try{await journeyApi(`/api/uploads/${f.id}`,'DELETE');setFiles(files.filter(x=>x.id!==f.id));}catch(e){setError((e as Error).message);}}}><Trash2 size={15}/></button></div>)}</div></section></div>{error&&<p className="error-banner" role="alert">{error}</p>}<div className="journey-save"><span>Save to apply your delivery settings and lesson attachments.</span><button className="button primary" disabled={busy} onClick={async()=>{setBusy(true);await onSave();setBusy(false);}}>{busy?<Loader2 size={16} className="spin"/>:<Check size={16}/>}Save delivery</button></div></div>;
}
