"use client";
import {useState} from 'react';
import {Plus,Trash2,FileCode2,Check} from 'lucide-react';
import {type Product,fileSchema} from '@/lib/product';
import {GrowingTextarea} from './product-flow';
export function FileWorkbench({product,onChange}:{product:Product;onChange:(p:Product)=>void}){
 const [selected,setSelected]=useState(0),files=product.content.files||[],f=files[selected];const set=(v:typeof files)=>onChange({...product,content:{...product.content,files:v}});
 return <div className="file-workbench"><div className="journey-heading"><div><span className="eyebrow">THE ACTUAL DELIVERABLES</span><h2>Useful files. Ready to work.</h2><p>Edit your templates, worksheets, and tools. File names are preserved in the package so code files can work together.</p></div><button className="button secondary" disabled={files.length>=20} onClick={()=>{set([...files,{name:`resource-${files.length+1}.md`,description:'',content:''}]);setSelected(files.length);}}><Plus size={16}/>Add file</button></div>{files.length?<div className="file-workbench-grid"><aside>{files.map((v,i)=><button key={i} className={selected===i?'active':''} onClick={()=>setSelected(i)}><FileCode2 size={18}/><span>{v.name}</span>{v.content.trim()&&<Check size={14}/>}</button>)}</aside>{f&&<section className="panel journey-card"><div className="form-stack"><label>File name<input value={f.name} maxLength={100} onChange={e=>set(files.map((v,i)=>i===selected?{...v,name:e.target.value}:v))}/><small>Supported: .md, .txt, .csv, .html, .json, .js, .css, .py. Use a unique filename.</small></label><label>What this file does<input value={f.description} maxLength={300} onChange={e=>set(files.map((v,i)=>i===selected?{...v,description:e.target.value}:v))}/></label><label>File content<GrowingTextarea className="source-editor" value={f.content} maxLength={100000} onChange={e=>set(files.map((v,i)=>i===selected?{...v,content:e.target.value}:v))}/></label><button className="text-link" onClick={()=>{set(files.filter((_,i)=>i!==selected));setSelected(Math.max(0,selected-1));}}><Trash2 size={16}/>Remove file</button>{!fileSchema.safeParse(f).success&&<p className="field-help">Check the filename and field lengths before saving.</p>}</div></section>}</div>:<div className="quiet-empty"><FileCode2 size={32}/><h3>Create something people can use.</h3><p>Add a worksheet or template, or generate your product’s supporting files with AI.</p></div>}</div>;
}
