"use client";
import {Video,Gift,CalendarDays,CheckCircle2,ShoppingBag,ArrowRight} from 'lucide-react';
import {toast} from 'sonner';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {initialBlocks,type Commerce,type FunnelBlock} from '@/lib/commerce';
import type {Product} from '@/lib/product';
const kinds=[{id:'sales',icon:ShoppingBag,title:'Product launch',body:'Story → offer → instant access'},{id:'vsl',icon:Video,title:'Video sales letter',body:'Watch → understand → buy'},{id:'free_guide',icon:Gift,title:'Free guide',body:'Useful free resource → new lead'},{id:'booking',icon:CalendarDays,title:'Book a meeting',body:'Get access → choose a time'},{id:'post_booking',icon:CheckCircle2,title:'Booking + follow-up',body:'Book → prepare → show up'}] as const;
export function FunnelPresets({product,products,onChange}:{product:Product;products:Product[];onChange:(value:Partial<Commerce['funnel']>)=>void}){
 const f=product.commerce!.funnel;
 function choose(kind:Commerce['funnel']['kind']){const before={...f},base=initialBlocks(product.title,product.description,product.content.benefits);const blocks:FunnelBlock[]=kind==='vsl'?[base[0],{id:crypto.randomUUID(),kind:'video',title:'See what you’ll learn',body:'',image:'',visible:true,align:'center'},base[1],base[2]]:base;
 if(kind==='free_guide'){blocks[2]={...blocks[2],title:'Start with something useful.',body:'Get the free guide and take your first step.'};}
 if(kind==='booking'||kind==='post_booking'){blocks[2]={...blocks[2],title:'Make time for your next step.',body:'Get access, then choose a time from the host’s availability.'};}
 onChange({kind,enabled:true,blocks,cta:kind==='free_guide'?'Get my free guide':kind==='booking'||kind==='post_booking'?'Get access & book':'Get instant access'});toast.success('Funnel layout applied',{action:{label:'Undo',onClick:()=>onChange(before)}});
 }
 return <section className="funnel-recipes"><div className="journey-heading"><div><h3>Start with the journey you want.</h3><p>Choose a layout, then make every section your own.</p></div></div><div className="funnel-recipe-grid">{kinds.map(({id,icon:Icon,title,body})=><button key={id} className={f.kind===id?'selected':''} onClick={()=>choose(id)}><Icon size={23}/><strong>{title}</strong><span>{body}</span>{f.kind===id&&<small>Selected</small>}</button>)}</div>{f.kind==='free_guide'&&<div className="form-two"><label>Free product to deliver<Select value={f.leadProductId||'self'} onValueChange={v=>onChange({leadProductId:v==='self'?'':v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="self">This product · must be free</SelectItem>{products.filter(p=>p.id!==product.id&&p.status==='published'&&p.price===0).map(p=><SelectItem key={p.id} value={p.id}>{p.title}</SelectItem>)}</SelectContent></Select></label><label>Thank-you message<textarea rows={2} maxLength={1500} value={f.thankYou} onChange={e=>onChange({thankYou:e.target.value})}/></label></div>}{['booking','post_booking'].includes(f.kind)&&<p className="journey-note"><CalendarDays size={16}/>Enable bookings, add available times, and customize the confirmation in Delivery. Customers keep access to the course or resources after booking.</p>}{f.kind==='vsl'&&<p className="journey-note"><Video size={16}/>Select the video section below and attach your sales video. Your uploaded sales video becomes public when this funnel is published.</p>}</section>;
}
