'use client';

import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowDownToLine,ArrowLeft,ArrowRight,ArrowUp,BookOpen,Check,CheckCircle2,ChevronRight,Coins,FileText,FolderOpen,ImagePlus,Layers3,Link2,Loader2,MessageSquare,Plus,Search,Settings2,ShieldCheck,Sparkles,Video,WandSparkles,X} from 'lucide-react';
import {Toaster,toast} from 'sonner';
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Brand,Cover} from './ui-brand';
import {AIProviders,GenerationProgress,MediaStudio} from './ai-components';
import {CreditsPanel} from './credits-panel';
import {ConnectionsPanel} from './connections-panel';
import {FileWorkbench} from './file-workbench';
import {StudioChat} from './studio-chat';
import {GrowingTextarea} from './product-flow';
import {emptyContent,type Product} from '@/lib/product';
import {studioFormats,type StudioConversation} from '@/lib/studio-plan';
import type {CreditBalance} from '@/lib/credit-policy';

type Workspace={admin:boolean;products:Product[];credits:CreditBalance;textCost:number;capabilities:{ai:boolean;media:boolean}};
type View='create'|'library'|'credits'|'connections'|'admin';
type HistoryItem={id:string;title:string;product_id:string|null;updated_at:number};
async function request<T>(url:string,body?:unknown,method=body?'POST':'GET'):Promise<T>{
  const response=await fetch(url,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});
  if(response.status===401||response.status===428){location.assign('/welcome?return_to='+encodeURIComponent(location.pathname+location.search));throw new Error('Please sign in to continue.');}
  const data=await response.json() as T&{error?:string};if(!response.ok)throw new Error(data.error||'Something went wrong. Please try again.');return data;
}
function readMessageDraft(id?:string|null){try{const saved=sessionStorage.getItem('fivegen:idea:'+(id||'new'));return saved!==null?saved:(!id?sessionStorage.getItem('fivegen:idea'):'')||'';}catch{return '';}}
const startingPoints=[
  {icon:BookOpen,name:'An original guide',kind:'Guide',prompt:'Help me create a practical guide about '},
  {icon:Video,name:'A course worth taking',kind:'Mini course',prompt:'I want to build a mini course that teaches '},
  {icon:Layers3,name:'Tools people will use',kind:'Template kit',prompt:'Create a template kit that helps '},
  {icon:WandSparkles,name:'Something entirely new',kind:'Custom product',prompt:'I have an idea for a digital tool: '},
];

export default function GeneratorStudio({user}:{user:{name:string;email:string}|null}){
  const [workspace,setWorkspace]=useState<Workspace|null>(null),[loading,setLoading]=useState(!!user),[error,setError]=useState('');
  const [view,setView]=useState<View>('create'),[conversation,setConversation]=useState<StudioConversation|null>(null),[history,setHistory]=useState<HistoryItem[]>([]),[remaining,setRemaining]=useState(20);
  const [draftReady,setDraftReady]=useState(false);
  const [message,setMessage]=useState(''),[busy,setBusy]=useState(''),[sent,setSent]=useState(''),[product,setProduct]=useState<Product|null>(null),[baseline,setBaseline]=useState(''),[editorTab,setEditorTab]=useState('content'),[section,setSection]=useState(0),[generating,setGenerating]=useState(false),[autoStart,setAutoStart]=useState(false);
  const [search,setSearch]=useState(''),[manual,setManual]=useState(false),[manualTitle,setManualTitle]=useState(''),[manualFormat,setManualFormat]=useState<(typeof studioFormats)[number]>('Guide'),[leave,setLeave]=useState<(()=>void)|null>(null);
  const inputRef=useRef<HTMLTextAreaElement>(null),busyRef=useRef(false);
  const dirty=!!product&&JSON.stringify(product)!==baseline;
  const load=useCallback(async()=>{if(!user)return;try{const data=await request<Workspace>('/api/workspace');setWorkspace(data);const plans=await request<{conversations:HistoryItem[];remaining:number}>('/api/studio/conversations');setHistory(plans.conversations);setRemaining(plans.remaining);setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[user]);
  useEffect(()=>{void load();const query=new URLSearchParams(location.search);if(query.has('billing'))setView('credits');if(query.get('connect')==='mcp')setView('connections');setMessage(readMessageDraft(query.get('conversation')));const id=query.get('conversation');if(id&&user)void openConversation(id);else setDraftReady(true);},[load]);
  useEffect(()=>{if(!draftReady)return;try{const id=conversation?.id||new URLSearchParams(location.search).get('conversation');sessionStorage.setItem('fivegen:idea:'+(id||'new'),message);}catch{}},[message,conversation?.id,draftReady]);
  useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(dirty||generating||busy){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty,generating,busy]);
  function navigate(action:()=>void){if(generating||busyRef.current){toast.info('Wait for the current step, or pause generation first.');return;}if(dirty){setLeave(()=>action);return;}action();}
  function changeView(next:View){navigate(()=>{if(next==='create'&&conversation)conversationReplace(conversation.id);else historyReplace();setProduct(null);setView(next);setError('');});}
  function newIdea(){navigate(()=>{setProduct(null);setConversation(null);setMessage('');setView('create');setError('');historyReplace();inputRef.current?.focus();});}
  function conversationReplace(id:string){window.history.replaceState(null,'','/?conversation='+encodeURIComponent(id));}
  function historyReplace(id?:string){window.history.replaceState(null,'',id?'/?project='+encodeURIComponent(id):'/');}
  const receiveProduct=useCallback((p:Product)=>{setProduct(p);setBaseline(JSON.stringify(p));setWorkspace(w=>w?{...w,products:[p,...w.products.filter(v=>v.id!==p.id)]}:w);},[]);
  function openProduct(p:Product){navigate(()=>{receiveProduct(p);setView('library');setEditorTab('content');setSection(0);setAutoStart(false);setError('');historyReplace(p.id);});}
  useEffect(()=>{const id=new URLSearchParams(location.search).get('project');if(id&&workspace&&!product){const p=workspace.products.find(v=>v.id===id);if(p){receiveProduct(p);setView('library');}}},[workspace,product,receiveProduct]);
  async function openConversation(id:string){navigate(()=>{setDraftReady(false);setBusy('history');busyRef.current=true;void request<{conversation:StudioConversation;remaining:number}>('/api/studio/conversations?id='+encodeURIComponent(id)).then(data=>{setConversation(data.conversation);setMessage(readMessageDraft(data.conversation.id));setRemaining(data.remaining);setProduct(null);setView('create');setError('');conversationReplace(data.conversation.id);}).catch(e=>setError(e.message)).finally(()=>{setDraftReady(true);setBusy('');busyRef.current=false;});});}
  async function send(promptValue=message):Promise<boolean>{
    const prompt=promptValue.trim();
    if(busyRef.current||prompt.length<3||prompt.length>3000)return false;
    if(!user){location.assign('/signin-with-chatgpt?return_to=%2F');return false;}
    const draft=message;busyRef.current=true;setBusy('planning');setError('');setSent(prompt);setMessage('');
    try{const data=await request<{conversation:StudioConversation;remaining:number}>('/api/studio/conversations',{id:conversation?.id||crypto.randomUUID(),requestId:crypto.randomUUID(),message:prompt,expectedUpdatedAt:conversation?.updatedAt||0,maxCredits:remaining>0?0:workspace?.textCost||10});setConversation(data.conversation);conversationReplace(data.conversation.id);setRemaining(data.remaining);void load();return true;}
    catch(e){setError((e as Error).message);setMessage(draft);return false;}finally{setBusy('');setSent('');busyRef.current=false;}
  }
  async function create(manualMode=false){
    if(busyRef.current)return;if(!user){location.assign('/signin-with-chatgpt?return_to=%2F');return;}
    busyRef.current=true;setBusy('create');setError('');
    try{const data=await request<{product:Product}>('/api/products',manualMode?{title:manualTitle,description:'A private product draft. Add your own description and content.',audience:'Define your audience',format:manualFormat,price:0,color:'orange',generationMode:'manual'}:{conversationId:conversation?.id,expectedUpdatedAt:conversation?.updatedAt});receiveProduct(data.product);setManual(false);setSection(0);setEditorTab('content');setView('library');setAutoStart(!manualMode);historyReplace(data.product.id);if(conversation&&!manualMode)setConversation({...conversation,productId:data.product.id});void load();}
    catch(e){setError((e as Error).message);}finally{setBusy('');busyRef.current=false;}
  }
  const save=useCallback(async()=>{if(!product)return false;if(!dirty)return true;busyRef.current=true;setBusy('save');setError('');try{const {commerce:_commerce,experience:_experience,status:_status,...fields}=product;const data=await request<{product:Product}>(`/api/products/${product.id}`,{...fields,status:'draft',expectedUpdatedAt:product.updatedAt},'PATCH');receiveProduct(data.product);toast.success('All changes saved');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy('');busyRef.current=false;}},[product,dirty,receiveProduct]);
  const onComplete=useCallback(()=>{setAutoStart(false);void load();toast.success('Your product is ready. Review it, then create its visuals.');},[load]);
  const costs=workspace?.textCost||10;
  const allowed=workspace?.credits.products.remaining??3;
  const unlimited=!!workspace?.credits.unlimited;
  const nav=[{id:'create' as const,label:'Create',icon:Sparkles},{id:'library' as const,label:'My products',icon:FolderOpen},{id:'credits' as const,label:'AI credits',icon:Coins},{id:'connections' as const,label:'Connect assistant',icon:Link2}];

  return <div className={`gen-app ${view==='create'&&!product&&(conversation||sent)?'gen-chat-active':''}`}><Toaster position="bottom-right" theme="dark" richColors/>
    <aside className="gen-sidebar"><a className="gen-logo" href="/" aria-label="FiveGen home"><Brand/></a><span className="gen-workspace-label">YOUR CREATIVE OPERATING SYSTEM</span>
      <button className="gen-new" onClick={newIdea}><Plus size={17}/>New idea <span>+</span></button>
      <nav aria-label="Main navigation">{nav.map(n=><button key={n.id} className={view===n.id?'active':''} aria-current={view===n.id?'page':undefined} onClick={()=>changeView(n.id)}><n.icon size={18}/>{n.label}{n.id==='library'&&!!workspace?.products.length&&<small>{workspace.products.length}</small>}</button>)}</nav>
      {!!history.length&&<div className="gen-recents"><span>RECENT IDEAS</span>{history.slice(0,5).map(h=><button key={h.id} title={h.title} onClick={()=>void openConversation(h.id)}><MessageSquare size={14}/><span>{h.title}</span></button>)}</div>}
      <div className="gen-sidebar-bottom"><div className="gen-allowance"><div><Sparkles size={15}/><strong>{unlimited?'Unlimited generation':`${user?allowed:3} free AI products`}</strong></div><p>{unlimited?'Your account has full AI access.':'Fresh possibilities, every month.'}</p>{!unlimited&&<a href="/pricing">Explore plans & credits <ArrowRight size={14}/></a>}</div>
        {workspace?.admin&&<button className="gen-admin-link" onClick={()=>changeView('admin')}><ShieldCheck size={15}/>Platform settings</button>}
        <div className="gen-account"><span>{user?.name?.[0]||'F'}</span><div><strong>{user?.name||'Your next big idea'}</strong><a href={user?'/account/billing':'/signin-with-chatgpt?return_to=%2F'}>{user?'Account & billing':'Sign in to your studio'}</a></div></div>
      </div>
    </aside>
    <div className="gen-main"><header className="gen-topbar"><div><span className="gen-brand-mobile"><Brand/></span><span className="gen-breadcrumb">Studio <ChevronRight size={13}/><strong>{product?'Product editor':{create:'Create with AI',library:'My products',credits:'AI credits',connections:'Connected assistants',admin:'Platform settings'}[view]}</strong></span></div><div className="gen-topbar-actions"><span className="gen-private"><ShieldCheck size={14}/>Private workspace</span><a className="gen-credit-pill" href={unlimited?'/account/billing':'/pricing'}><Coins size={15}/>{unlimited?'Unlimited':`${workspace?workspace.credits.total.toLocaleString():'Get'} credits`}{!unlimited&&<Plus size={13}/>}</a>{!user&&<a className="gen-signin" href="/signin-with-chatgpt?return_to=%2F">Sign in <ArrowRight size={14}/></a>}</div></header>
      <div className="gen-mobile-nav">{nav.map(n=><button key={n.id} aria-label={n.label} className={view===n.id?'active':''} onClick={()=>changeView(n.id)}><n.icon size={16}/>{n.id==='connections'?'Connect':n.id==='credits'?'Credits':n.label}</button>)}</div>
      {error&&<div className="gen-error" role="alert"><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
      {loading||busy==='history'?<div className="gen-loading"><Loader2 size={28} className="spin"/><p>Opening your creative workspace…</p></div>:product?<div className="gen-editor gen-enter">
        <div className="gen-editor-heading"><button className="gen-back" onClick={()=>changeView('library')}><ArrowLeft size={16}/>All products</button><div className="gen-save-actions"><span aria-live="polite">{generating?'AI is creating…':dirty?'Unsaved changes':'Saved privately'}</span><button className="button secondary" disabled={!dirty||!!busy||generating} onClick={()=>void save()}>{busy==='save'?<Loader2 className="spin" size={15}/>:<Check size={15}/>}Save changes</button><button className="button primary" disabled={!!busy||generating||(!product.content.sections.some(s=>s.body.trim())&&!product.content.files?.some(f=>f.content.trim()))} onClick={async()=>{if(await save())location.assign(`/api/products/${product.id}/bundle`);}}><ArrowDownToLine size={15}/>Download</button></div></div>
        <div className="gen-editor-title"><span className="gen-tag">{product.format} <span>·</span> PRIVATE PROJECT</span><h1>{product.title}</h1><p>Make it yours. Every section and supporting file is editable.</p></div>
        <GenerationProgress key={product.id} product={product} textCost={costs} aiReady={!!workspace?.capabilities.ai} autoStart={autoStart} onProduct={receiveProduct} onComplete={onComplete} onSetup={()=>changeView('credits')} onBeforeGenerate={save} onRunningChange={setGenerating} onAllowance={allowance=>setWorkspace(w=>w?{...w,credits:{...w.credits,products:allowance}}:w)}/>
        <div className="gen-editor-tabs" role="tablist" aria-label="Product editor">{[['content',FileText,'Product content'],['files',Layers3,'Supporting files'],['media',ImagePlus,'Images & video'],['launch',WandSparkles,'Launch copy']].map(([key,Icon,label])=>{const I=Icon as typeof FileText;return <button role="tab" aria-selected={editorTab===key} key={String(key)} onClick={()=>setEditorTab(String(key))}><I size={17}/>{String(label)}</button>;})}</div>
        <div role="tabpanel" className="gen-tab-content">
        {editorTab==='content'&&<div className="gen-document-grid"><aside className="gen-outline"><span>IN THIS PRODUCT</span>{product.content.sections.map((s,i)=><button className={section===i?'active':''} key={s.id||i} onClick={()=>setSection(i)}><small>{String(i+1).padStart(2,'0')}</small><span>{s.title||'Untitled section'}</span>{s.body.trim()&&<Check size={13}/>}</button>)}<button disabled={generating||busy==='save'||product.content.sections.length>=30} onClick={()=>{setProduct({...product,content:{...product.content,sections:[...product.content.sections,{id:crypto.randomUUID(),title:'New section',body:''}]}});setSection(product.content.sections.length);}}><Plus size={15}/>Add section</button><details><summary>Product details</summary><label>Title<input value={product.title} maxLength={100} disabled={generating||busy==='save'} onChange={e=>setProduct({...product,title:e.target.value})}/></label><label>Who it is for<input value={product.audience} maxLength={300} disabled={generating||busy==='save'} onChange={e=>setProduct({...product,audience:e.target.value})}/></label><label>About this product<GrowingTextarea value={product.description} maxLength={12000} disabled={generating||busy==='save'} onChange={e=>setProduct({...product,description:e.target.value})}/></label></details></aside>
          <section className="gen-document">{product.content.sections[section]&&<><div className="gen-document-meta"><span>SECTION {String(section+1).padStart(2,'0')}</span><span>{product.content.sections[section].body.trim().split(/\s+/).filter(Boolean).length} words</span></div><input aria-label="Section title" className="gen-section-title" value={product.content.sections[section].title} maxLength={150} disabled={generating||busy==='save'} onChange={e=>setProduct({...product,content:{...product.content,sections:product.content.sections.map((s,i)=>i===section?{...s,title:e.target.value}:s)}})}/>{product.content.sections[section].objective&&<p className="gen-section-objective">{product.content.sections[section].objective}</p>}<GrowingTextarea aria-label="Section content" className="gen-section-body" placeholder="Your finished content appears here as AI writes. You can also write it yourself." value={product.content.sections[section].body} maxLength={18000} disabled={generating||busy==='save'} onChange={e=>setProduct({...product,content:{...product.content,sections:product.content.sections.map((s,i)=>i===section?{...s,body:e.target.value}:s)}})}/><div className="gen-document-footer"><span><ShieldCheck size={14}/>Saved in your private workspace.</span><button className="gen-text-button" disabled={generating||!!busy||product.content.sections.length<2} onClick={()=>{const sections=product.content.sections.filter((_,i)=>i!==section);setProduct({...product,content:{...product.content,sections}});setSection(Math.min(section,sections.length-1));}}>Remove section</button><button className="gen-text-button" disabled={section===product.content.sections.length-1} onClick={()=>setSection(section+1)}>Next section <ArrowRight size={15}/></button></div></>}</section></div>}
        {editorTab==='files'&&<fieldset disabled={generating||busy==='save'}><FileWorkbench product={product} onChange={setProduct}/><div className="gen-download-links">{product.content.files?.map((f,i)=><button className="button secondary" key={i} disabled={dirty||generating} onClick={()=>location.assign(`/api/products/${product.id}/files/${i}`)}><ArrowDownToLine size={15}/>{f.name}</button>)}{dirty&&<p>Save your changes to download the updated files.</p>}</div></fieldset>}
        {editorTab==='media'&&<MediaStudio key={product.id} product={product} onSetup={()=>changeView('credits')}/>}
        {editorTab==='launch'&&<div className="gen-launch"><div className="gen-section-intro"><WandSparkles size={22}/><div><h2>Give your creation a voice.</h2><p>Editable copy to take with you wherever you share your work.</p></div></div><label>Product description & presentation copy<GrowingTextarea value={product.content.salesCopy||''} disabled={generating||busy==='save'} maxLength={15000} placeholder="AI prepares tailored copy in the final generation step." onChange={e=>setProduct({...product,content:{...product.content,salesCopy:e.target.value}})}/></label><label>Campaign & launch resources<GrowingTextarea value={product.content.launch} disabled={generating||busy==='save'} maxLength={50000} placeholder="Your emails, social posts and launch calendar appear here." onChange={e=>setProduct({...product,content:{...product.content,launch:e.target.value}})}/></label></div>}
        </div><div className="gen-editor-next"><ImagePlus size={21}/><div><strong>Bring this product to life.</strong><p>{unlimited?'Create original product images and videos with your unlimited access.':'Create an original product image for 12 credits, or a 5-second video for 160.'}</p></div><button className="button secondary" onClick={()=>{setEditorTab('media');window.scrollTo({top:0,behavior:'smooth'});}}>Open creative studio <ArrowRight size={15}/></button></div>
      </div>:view==='create'&&(conversation||sent)?<StudioChat key={conversation?.id||'new-chat'} conversation={conversation} message={message} sent={sent} busy={busy} name={user?.name||'You'} remaining={remaining} cost={costs} unlimited={unlimited} credits={workspace?.credits.total} allowance={allowed} aiReady={!!workspace?.capabilities.ai} onMessage={setMessage} onSend={send} onGenerate={()=>void create()} onOpenProduct={()=>{const p=workspace?.products.find(p=>p.id===conversation?.productId);if(p)openProduct(p);else void load();}}/>:view==='create'?<div className="gen-create gen-enter">
        <div className="gen-hero"><div className="gen-status"><span/>IDEA → INTELLIGENCE → CREATION</div><h1>What will you<br/><span>bring to life?</span></h1><p>A guide. A course. A tool nobody has made yet.<br/>Start with your idea. Build the whole thing with AI.</p></div>
        <div className="gen-planning-layout"><section className="gen-conversation">
          <form className="gen-composer" onSubmit={e=>{e.preventDefault();void send();}}><div className="gen-composer-top"><Sparkles size={18}/><span>Describe your idea. We’ll build the plan.</span><span className="gen-composer-mode">AI CREATIVE PARTNER</span></div><textarea ref={inputRef} aria-label="Your product idea" placeholder="A practical 7-day guide that helps freelance designers land their first client…" value={message} maxLength={3000} disabled={!!busy} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing&&!window.matchMedia('(pointer: coarse)').matches){e.preventDefault();void send();}}}/><div className="gen-composer-bottom"><span>{unlimited?'Unlimited AI planning':remaining>0?remaining+' planning messages included this month':costs+' credits per planning message'}<small>Enter to send · Shift + Enter for a new line</small></span><button type="submit" className="gen-send" disabled={message.trim().length<3||!!busy||(!unlimited&&remaining===0&&!!workspace&&workspace.credits.total<costs)} aria-label={unlimited||remaining>0?'Plan my product':'Send using '+costs+' credits'}><ArrowUp size={20}/><span>{unlimited||remaining>0?'Let’s create':'Send · '+costs+' credits'}</span></button></div></form>
          <div className="gen-starting-points">{startingPoints.map(p=><button key={p.kind} disabled={!!busy} onClick={()=>{setMessage(p.prompt);inputRef.current?.focus();}}><p.icon size={20}/><span>{p.name}</span><ArrowRight size={15}/></button>)}</div><div className="gen-start-manual"><span>Already know what you’re making?</span><button onClick={()=>setManual(true)}>Start a blank product <ArrowRight size={14}/></button></div>
        </section></div>
        <section className="gen-workflow"><div><span>01</span><strong>Think it through.</strong><p>AI helps define what to make and who it is for.</p></div><div><span>02</span><strong>Make the real thing.</strong><p>Full content, practical resources, and editable files.</p></div><div><span>03</span><strong>Give it an identity.</strong><p>Original images and video. Ready to download.</p></div></section>
      </div>:view==='library'?<div className="gen-library gen-enter"><div className="gen-page-heading"><div><span className="gen-tag">YOUR IDEAS, MADE TANGIBLE</span><h1>My products<span>{workspace?.products.length||0}</span></h1><p>Your content, supporting files, and creative assets. All in one place.</p></div><button className="button primary" onClick={newIdea}><Plus size={16}/>New product</button></div><div className="gen-library-tools"><label><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a product…" aria-label="Search products"/></label><button className="button secondary" onClick={()=>setManual(true)}><FileText size={16}/>Blank product</button></div><div className="gen-product-grid">{workspace?.products.filter(p=>(p.title+' '+p.format).toLowerCase().includes(search.toLowerCase())).map(p=><button className="gen-product-card" key={p.id} onClick={()=>openProduct(p)}><Cover product={p}/><div><span className="gen-product-type">{p.format}<span>{p.content.sections.length>0&&p.content.sections.every(s=>s.body.trim())?'Ready to review':p.content.sections.some(s=>s.body.trim())?'In progress':'Draft'}</span></span><h2>{p.title}</h2><p>{p.content.sections.length} sections · {p.content.files?.length||0} files</p><span className="gen-product-open">Open project <ArrowRight size={16}/></span></div></button>)}</div>{!workspace?.products.length&&<div className="gen-empty"><span><FolderOpen size={32}/></span><h2>Your ideas deserve to exist.</h2><p>Describe the first one. FiveGen will help turn it into something useful.</p><button className="button primary" onClick={newIdea}>Create my first product <ArrowRight size={16}/></button></div>}{!!workspace?.products.length&&!workspace.products.some(p=>(p.title+' '+p.format).toLowerCase().includes(search.toLowerCase()))&&<div className="gen-empty"><Search size={28}/><h2>No matching products.</h2><button className="button secondary" onClick={()=>setSearch('')}>Clear search</button></div>}</div>:<div className="gen-settings gen-enter">{view==='credits'?<CreditsPanel signedIn={!!user}/>:view==='connections'?<ConnectionsPanel signedIn={!!user}/>:workspace?.admin?<AIProviders signedIn={!!user} onUpdate={()=>void load()}/>:null}</div>}
      <footer className="gen-footer"><span>FiveGen · Your next idea, made real.</span><div><a href="/pricing">Plans & credits</a><a href="/terms">Terms</a><a href="/privacy">Privacy</a><a href="/refund">Refunds</a><a href="mailto:kamzewac@gmail.com">Contact</a></div></footer>
    </div>
    <Dialog open={manual} onOpenChange={v=>{if(!busy)setManual(v);}}><DialogContent><DialogHeader><DialogTitle>A blank canvas. Your expertise.</DialogTitle><DialogDescription>Create a private, editable product without using AI credits.</DialogDescription></DialogHeader><form className="gen-manual-form" onSubmit={e=>{e.preventDefault();void create(true);}}><label>Product name<input autoFocus minLength={3} maxLength={100} required value={manualTitle} onChange={e=>setManualTitle(e.target.value)} placeholder="Give your idea a name"/></label><label>Format<select value={manualFormat} onChange={e=>setManualFormat(e.target.value as typeof manualFormat)}>{studioFormats.map(f=><option key={f}>{f}</option>)}</select></label><button className="button primary full" disabled={!!busy||manualTitle.trim().length<3}>{busy==='create'?<Loader2 size={16} className="spin"/>:<Plus size={16}/>}Create blank product</button></form></DialogContent></Dialog>
    <Dialog open={!!leave} onOpenChange={v=>{if(!v)setLeave(null);}}><DialogContent><DialogHeader><DialogTitle>Keep your latest changes?</DialogTitle><DialogDescription>Your product has unsaved edits. Save them before moving on.</DialogDescription></DialogHeader><DialogFooter><button className="button secondary" onClick={()=>{const action=leave;setLeave(null);action?.();}}>Discard edits</button><button className="button primary" disabled={!!busy} onClick={async()=>{if(await save()){const action=leave;setLeave(null);action?.();}}}>Save & continue</button></DialogFooter></DialogContent></Dialog>
  </div>;
}
