"use client";
import {useState,useEffect} from 'react';
import {ArrowRight,CheckCircle2,Loader2} from 'lucide-react';
export function LeadForm({slug,cta}:{slug:string;cta:string}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<{url:string;message:string;nextUrl?:string}|null>(null);
 useEffect(()=>{void fetch('/api/visits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug})});},[slug]);
 return result?<div className="lead-success"><CheckCircle2 size={32}/><h3>Your next step is ready.</h3><p>{result.message}</p><a className="button primary" href={result.url}>Open your free guide <ArrowRight size={16}/></a>{result.nextUrl&&<a className="text-link" href={result.nextUrl}>Explore the complete product</a>}</div>:<form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slug,name:f.get('name'),email:f.get('email'),marketing:f.get('marketing')==='on',website:f.get('website')})});const d=await r.json() as any;if(!r.ok)throw new Error(d.error);setResult(d);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <label>Your name<input name="name" autoComplete="name" maxLength={100} required/></label><label>Email address<input name="email" type="email" autoComplete="email" maxLength={200} required/></label><div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="consent-label"><input name="marketing" type="checkbox"/>I’d also like product news from this creator. Optional.</label><small>Your details save your access and help the creator follow up about this guide.</small>{error&&<p className="error-banner" role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy?<Loader2 size={16} className="spin"/>:<ArrowRight size={16}/>} {busy?'Preparing your guide…':cta||'Get my free guide'}</button></form>;
}
