"use client";
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,CalendarDays,Check,CheckCircle2,Download,Loader2,MessageCircle,Pin,Plus,Trash2,Users} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Brand} from './ui-brand';
import {journeyApi} from './delivery-panel';
import {recipeFor} from '@/lib/product-recipes';
import type {Product} from '@/lib/product';
type Room={bookingCredits:number;product:Product;owner:boolean;userId:string;progress:string[];posts:any[];slots:any[];bookings:any[];uploads:any[]};
export default function LearningRoom({slug}:{slug:string}){
 const [room,setRoom]=useState<Room|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[section,setSection]=useState(0),[tab,setTab]=useState('learn'),[body,setBody]=useState(''),[reply,setReply]=useState<string|null>(null),[slot,setSlot]=useState(''),[notes,setNotes]=useState('');
 const load=()=>journeyApi<Room>(`/api/learn/${slug}`).then(d=>{setRoom(d);return d;});
 useEffect(()=>{void load().catch(e=>setError(e.message));},[slug]);
 async function action(data:any){setBusy(true);setError('');try{await journeyApi(`/api/learn/${slug}`,'POST',data);await load();return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 if(!room)return <div className="member-shell"><nav><a href="/"><Brand/></a></nav><main className="member-access"><BookOpen size={36}/><h1>{error?'Let’s find your access.':'Opening your product…'}</h1><p>{error||'Your lessons and progress will be ready in a moment.'}</p>{error&&<><a className="button primary" href={`/p/${slug}`}>View product</a><a className="text-link" href={`/signout-with-chatgpt?return_to=${encodeURIComponent('/learn/'+slug)}`}>Use a different purchase email</a></>}</main></div>;
 const p=room.product,e=p.experience!,r=recipeFor(p.format),s=p.content.sections[section],lessonId=s?.id||String(section),completed=room.progress.includes(lessonId),percent=Math.round(room.progress.length/p.content.sections.length*100),booking=room.bookings.find(b=>b.status==='confirmed')||(room.bookingCredits===0?room.bookings.find(b=>b.status!=='cancelled'):null);
 return <div className="member-shell"><nav><a href="/"><Brand/></a><span>{room.owner?'Creator preview':'YOUR MEMBER SPACE'}</span><a className="text-link" href={`/p/${slug}`}>Product details</a></nav><header className="member-heading"><div><span className="eyebrow">{r.label.toUpperCase()}</span><h1>{p.title}</h1><p>{p.description}</p></div><div className="member-progress"><strong>{Math.min(percent,100)}% complete</strong><Progress value={Math.min(percent,100)}/><span>{room.progress.length} of {p.content.sections.length} {r.unit.toLowerCase()}s</span></div></header>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="member-tabs"><TabsTrigger value="learn"><BookOpen size={16}/>{p.format==='Mini course'?'Classroom':'Your product'}</TabsTrigger><TabsTrigger value="resources"><Download size={16}/>Resources</TabsTrigger>{e.booking.enabled&&<TabsTrigger value="booking"><CalendarDays size={16}/>Your booking</TabsTrigger>}{e.community.enabled&&<TabsTrigger value="community"><Users size={16}/>Community</TabsTrigger>}</TabsList></Tabs>{error&&<p className="error-banner" role="alert">{error}</p>}
 {tab==='learn'&&<main className="classroom-grid"><aside className="lesson-outline"><h2>{p.format==='Mini course'?'Your curriculum':'Your path'}</h2>{p.content.sections.map((v,i)=><button className={i===section?'active':''} key={v.id||i} onClick={()=>setSection(i)}><span>{room.progress.includes(v.id||String(i))?<CheckCircle2 size={19}/>:String(i+1).padStart(2,'0')}</span><div><small>{r.unit} {i+1}{v.videoId?' · Video':''}</small><strong>{v.title}</strong></div></button>)}</aside><article className="lesson-reader" key={lessonId}>{s.videoId&&<video className="class-video" controls playsInline preload="metadata" src={`/api/uploads/${s.videoId}`}/>}<span className="eyebrow">{r.unit.toUpperCase()} {section+1}</span><h2>{s.title}</h2>{s.objective&&<p className="lesson-objective">{s.objective}</p>}<div className="reading-content">{s.body.split('\n\n').filter(Boolean).map((text,i)=><p key={i}>{text}</p>)}</div><div className="lesson-footer"><button className="button secondary" disabled={section===0} onClick={()=>setSection(section-1)}><ArrowLeft size={16}/>Previous</button><button className="button primary" disabled={busy} onClick={async()=>{if(await action({action:'complete',lessonId,complete:!completed})&&!completed&&section<p.content.sections.length-1)setSection(section+1);}}>{busy?<Loader2 size={16} className="spin"/>:<Check size={16}/>} {completed?'Mark incomplete':section===p.content.sections.length-1?'Complete product':'Complete & continue'}</button></div>{percent>=100&&<div className="completion-note"><CheckCircle2 size={24}/><div><h3>You did the work. Now put it to use.</h3><p>Return to any lesson, download your resources, or share a question with the community.</p></div></div>}</article></main>}
 {tab==='resources'&&<main className="member-resources"><h2>Your working materials</h2><p>Keep these resources close as you put the product into practice.</p><a className="button primary" href={`/api/member-download/${slug}`}><Download size={16}/>Download product package</a><div className="resource-list">{room.uploads.map(f=><div key={f.id}><a href={`/api/uploads/${f.id}?download=1`}>{f.name}</a><span>{(f.size/1024/1024).toFixed(1)} MB</span></div>)}</div>{!room.uploads.length&&<p className="field-help">The complete package includes the written product and any generated supporting files.</p>}</main>}
 {tab==='booking'&&<main className="member-booking">{booking?<><div className="booking-confirmation"><CheckCircle2 size={34}/><span className="eyebrow">{booking.status==='confirmed'?'BOOKING CONFIRMED':booking.status==='attended'?'SESSION COMPLETED':'SESSION MISSED'}</span><h2>{booking.status==='confirmed'?e.booking.confirmationTitle:'Your session record'}</h2><p className="booking-time">{new Date(booking.starts_at).toLocaleString(undefined,{dateStyle:'full',timeStyle:'short'})}<span>{booking.duration} minutes · {Intl.DateTimeFormat().resolvedOptions().timeZone}</span></p><p>{e.booking.confirmationBody}</p><div className="booking-actions"><a className="button secondary" href={`/api/bookings/${booking.id}/calendar`}>Add to calendar</a>{e.booking.meetingUrl&&<a className="button primary" href={e.booking.meetingUrl} target="_blank" rel="noreferrer">Open meeting <ArrowRight size={16}/></a>}</div>{!e.booking.meetingUrl&&<p className="field-help">Your host will provide the meeting link.</p>}{booking.status==='confirmed'&&booking.starts_at>Date.now()&&<details><summary>Need to change your time?</summary><p>Cancel this time, then choose another available slot.</p><button className="button secondary" disabled={busy} onClick={()=>void action({action:'cancel',id:booking.id})}>Cancel booking</button></details>}</div><section className="booking-preparation"><h3>Come prepared</h3><p>{e.booking.preparation||'Review your product resources and bring the questions that matter most to you.'}</p>{e.booking.confirmationVideoId&&<video controls playsInline src={`/api/uploads/${e.booking.confirmationVideoId}`}/>}<button className="text-link" onClick={()=>setTab('learn')}>Explore your resources <ArrowRight size={16}/></button></section></>:<section className="booking-picker"><span className="eyebrow">MAKE TIME FOR YOUR NEXT STEP</span><h2>Choose a time that works for you.</h2><p>Times are shown in {Intl.DateTimeFormat().resolvedOptions().timeZone}. You’ll receive a confirmation and calendar download.</p><div className="booking-slots">{room.slots.map(s=><button key={s.id} className={slot===s.id?'selected':''} onClick={()=>setSlot(s.id)}>{new Date(s.starts_at).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}<strong>{new Date(s.starts_at).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}</strong><small>{s.duration} min</small></button>)}</div>{!room.slots.length&&<div className="quiet-empty"><CalendarDays size={28}/><p>Your host hasn’t opened new times yet. Check back soon; your product access is saved.</p></div>}<label>What would you like to work on? <small>Optional</small><textarea rows={3} value={notes} maxLength={2000} onChange={e=>setNotes(e.target.value)}/></label><button className="button primary" disabled={!slot||busy} onClick={()=>void action({action:'book',slotId:slot,notes})}>{busy?<Loader2 size={16} className="spin"/>:<CalendarDays size={16}/>}Confirm booking</button></section>}</main>}
 {tab==='community'&&<main className="community-grid"><section><div className="community-welcome"><span className="eyebrow">BETTER TOGETHER</span><h2>Your community</h2><p>{e.community.welcome||'Ask a useful question, share what you tried, or help another member move forward.'}</p></div><form className="community-composer" onSubmit={async ev=>{ev.preventDefault();if(await action({action:'post',body,...(reply?{parentId:reply}:{})})){setBody('');setReply(null);}}}>{reply&&<div>Replying to a discussion <button type="button" className="text-link" onClick={()=>setReply(null)}>Cancel reply</button></div>}<label>{reply?'Your reply':'Start a conversation'}<textarea required rows={3} maxLength={5000} value={body} onChange={e=>setBody(e.target.value)} placeholder="A question, a useful discovery, or a step you’re proud of…"/></label><button className="button primary" disabled={busy||!body.trim()}><Plus size={16}/>{reply?'Post reply':'Post to community'}</button></form>{room.posts.filter(p=>!p.parent_id).map(post=><article className="community-post" key={post.id}><div className="post-meta"><span className="member-avatar">{post.name[0]}</span><strong>{post.name}</strong><time>{new Date(post.created_at).toLocaleDateString()}</time>{!!post.pinned&&<Pin size={15}/>}</div><p>{post.body}</p><div className="post-actions"><button className="text-link" onClick={()=>setReply(post.id)}><MessageCircle size={15}/>Reply</button>{room.owner&&<button className="text-link" disabled={busy} onClick={()=>void action({action:'pinPost',id:post.id,pinned:!post.pinned})}>{post.pinned?'Unpin':'Pin discussion'}</button>}{(room.owner||post.user_id===room.userId)&&<button className="icon-button" aria-label="Remove discussion" disabled={busy} onClick={()=>void action({action:'deletePost',id:post.id})}><Trash2 size={15}/></button>}</div>{room.posts.filter(r=>r.parent_id===post.id).map(r=><div className="community-reply" key={r.id}><strong>{r.name}</strong><p>{r.body}</p>{(room.owner||r.user_id===room.userId)&&<button className="text-link" onClick={()=>void action({action:'deletePost',id:r.id})}>Remove reply</button>}</div>)}</article>)}{!room.posts.length&&<div className="quiet-empty"><MessageCircle size={30}/><h3>A good conversation starts with one person.</h3><p>Introduce yourself and tell the group what you’re working toward.</p></div>}</section><aside className="community-guidelines"><Users size={24}/><h3>A space worth returning to.</h3><p>{e.community.rules}</p><small>Private to this product’s customers and creator.</small></aside></main>}
 </div>;
}
