"use client";
import { useEffect, useState } from "react";
import { ArrowDown, ArrowUp, ArrowUpRight, Check, Copy, Crown, Eye, EyeOff, Layers3, Loader2, LockKeyhole, Plus, Trash2, WandSparkles } from "lucide-react";
import { Tabs,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Dialog,DialogContent,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { toast } from "sonner";
import { commerceSchema, defaultCommerce, dealNames, dealTypes, initialBlocks, type Commerce, type FunnelBlock } from "@/lib/commerce";
import { plans, type PlanInfo } from "@/lib/plans";
import { money,type Product } from "@/lib/product";
import {CreditsPanel} from "./credits-panel";
import { FunnelView } from "./funnel-view";

function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:Array<[string,string]>;label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>;}
export function BillingPage({plan,onRefresh,signedIn}:{plan:PlanInfo;onRefresh:()=>void;signedIn:boolean}){
  const [interval,setInterval]=useState<"month"|"year">("month"),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{const q=new URLSearchParams(location.search);if(q.get("billing")==="success"&&q.get("session_id")){setBusy(true);fetch(`/api/billing?session_id=${encodeURIComponent(q.get("session_id")!)}`).then(async r=>{const d=await r.json() as {url:string;error?:string};if(!r.ok)throw new Error(d.error);onRefresh();toast.success("Welcome to FiveGen Pro");history.replaceState(null,"","/");}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}},[]);
  const checkout=async(action:"upgrade"|"portal")=>{if(!signedIn){location.href="/signin-with-chatgpt?return_to=/?billing=plans";return;}setBusy(true);setError("");try{const r=await fetch("/api/billing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,interval})});const d=await r.json() as {url:string;error?:string};if(!r.ok)throw new Error(d.error);location.href=d.url;}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <div className="billing-page"><section className="billing-intro"><span className="eyebrow">ROOM FOR YOUR NEXT BIG THING</span><h1>Start free. Grow on your terms.</h1><p>Build your first ten products for free. Unlock a complete sales studio when you’re ready.</p><div className="billing-cycle"><button className={interval==="month"?"active":""} onClick={()=>setInterval("month")}>Monthly</button><button className={interval==="year"?"active":""} onClick={()=>setInterval("year")}>Yearly <span>2 months free</span></button></div></section>
    {error&&<p className="error-banner" role="alert">{error}</p>}
    <div className="plan-grid">{(["free","pro"] as const).map(tier=><section key={tier} className={`plan-card ${tier==="pro"?"pro":""}`}><div className="plan-top"><span>{tier==="pro"?<Crown size={23}/>:<Layers3 size={23}/>}</span><span className="plan-label">{plan.tier===tier?"YOUR PLAN":tier==="pro"?"THE COMPLETE SALES STUDIO":"GET STARTED"}</span></div><h2>{plans[tier].name}</h2><p>{tier==="free"?"Your ideas deserve a beginning.":"Make every product a complete offer."}</p><div className="plan-price"><strong>{money((interval==="year"?plans[tier].yearly:plans[tier].monthly)*100)}</strong><span>/{interval==="year"?"year":"month"}</span></div><ul>{(tier==="free"?["Create and sell up to 10 products","1,200 one-time starter text credits","Standard product pages and shareable links","10% sales commission + processing fees","Product exports and revenue dashboard"]:["Create and sell up to 100 products","1,000 AI credits each month","Discounts, BOGO, bundles, and bonuses","Optional upsells at checkout","Custom funnel pages with live previews","Monthly and yearly product subscriptions", "3% sales commission + processing fees"]).map(v=><li key={v}><Check size={16}/>{v}</li>)}</ul>{tier==="pro"?<button className="button primary full" disabled={busy||(signedIn&&!plan.billingReady)} onClick={()=>void checkout(plan.tier==="pro"?"portal":"upgrade")}>{busy?<Loader2 className="spin" size={16}/>:<Crown size={16}/>} {plan.tier==="pro"?"Manage subscription":!plan.billingReady&&signedIn?"Billing setup required":"Get Pro"}</button>:<button className="button secondary full" disabled>{plan.tier==="free"?"You’re on Free":"Included in Pro"}</button>}</section>)}</div>
    <section className="plan-usage panel"><div><strong>{plan.used} of {plan.limit} products</strong><p>{plan.tier==="pro"&&plan.renewsAt?`${plan.cancelAtPeriodEnd?"Pro ends":"Next renewal"} ${new Date(plan.renewsAt).toLocaleDateString()}.`:"Drafts and published products both count toward your limit."}</p></div><div className="usage-meter"><span style={{width:`${Math.min(100,plan.used/plan.limit*100)}%`}}/></div>{plan.hasCustomer&&<button className="text-link" onClick={()=>void checkout("portal")} disabled={busy}>Manage billing <ArrowUpRight size={14}/></button>}</section>
    {!plan.billingReady&&<p className="billing-setup-note">Pro checkout opens once the platform owner configures Stripe billing and webhooks. Free creation and selling remain available.</p>}
    <CreditsPanel signedIn={signedIn}/><div className="plan-fineprint"><p><strong>Free: 10% commission. Pro: 3%.</strong> Stripe processing fees are separate. AI runs on FiveGen’s provider accounts; customers never need API keys. All prices are USD.</p><p><strong>Keep what you made.</strong> If you downgrade, products stay saved and basic pages keep working. Deals and funnels pause, new recurring sales pause, and creation follows the Free limit. Existing customer subscriptions continue in Stripe; their commission rate follows your plan at renewal. Purchased credits remain available.</p></div>
  </div>;
}

export function SalesTools({product,products,plan,onChange,onUpgrade}:{product:Product;products:Product[];plan:PlanInfo;onChange:(p:Product)=>void;onUpgrade:()=>void}){
  const [tab,setTab]=useState("offers"),[preview,setPreview]=useState(false),[selected,setSelected]=useState(0);
  const c=product.commerce||defaultCommerce(),f=c.funnel,d=c.deal,pro=plan.tier==="pro";
  const update=(values:Partial<Commerce>)=>onChange({...product,commerce:{...c,...values}});
  const funnel=(values:Partial<Commerce["funnel"]>)=>update({funnel:{...f,...values}});
  const related=products.filter(p=>p.id!==product.id&&p.status==="published"&&(!p.commerce||p.commerce.billing==="once"));
  const references:[[string,string],...[string,string][]]=[["none","Choose a published product"],...related.map(p=>[p.id,`${p.title} · ${money(p.price*100)}`] as [string,string])];
  const setBlock=(values:Partial<FunnelBlock>)=>funnel({blocks:f.blocks.map((b,i)=>i===selected?{...b,...values}:b)});
  const errors=commerceSchema.safeParse(c);
  if(!pro)return <section className="sales-locked panel"><span className="sales-lock-symbol"><Crown size={29}/></span><span className="eyebrow">FIVEGEN PRO</span><h2>Turn a product into an offer.</h2><p>Add a deal, pair it with an upsell, and tell its story on a page you design.</p><div className="locked-feature-grid">{["BOGO & bundles","Discounts & flash sales","Checkout upsells","Custom funnel pages","Recurring subscriptions","100 products"].map(v=><span key={v}><LockKeyhole size={15}/>{v}</span>)}</div><button className="button primary" onClick={onUpgrade}>Explore Pro · $29/month <ArrowUpRight size={17}/></button><small>Your standard storefront and selling tools are included in Free.</small></section>;
  return <div className="sales-tools"><div className="sales-tools-heading"><div><span className="eyebrow">YOUR SALES STUDIO</span><h2>Make an offer worth saying yes to.</h2></div><span className="pro-pill"><Crown size={12}/>PRO</span></div><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="offers">Pricing & deals</TabsTrigger><TabsTrigger value="funnel">Funnel page</TabsTrigger></TabsList></Tabs>
    {tab==="offers"?<div className="offer-editor-grid"><section className="panel sales-panel"><div className="sales-panel-heading"><span className="step-number">01</span><div><h3>How customers pay</h3><p>Choose a one-time purchase or ongoing access.</p></div></div><div className="form-two"><label>Price · USD<input type="number" min={0} max={9999} step="0.01" value={product.price} onChange={e=>onChange({...product,price:Number(e.target.value)})}/></label><label>Billing<Choice label="Billing frequency" value={c.billing} onChange={v=>update({billing:v as Commerce["billing"],...(v!=="once"?{deal:{...d,type:"none"},upsell:{...c.upsell,enabled:false}}:{})})} options={[["once","One-time purchase"],["month","Monthly subscription"],["year","Yearly subscription"]]}/></label></div>{c.billing!=="once"&&<div className="sales-note">Customers are charged {money(product.price*100)} every {c.billing==="month"?"month":"year"} until they cancel. Active subscriptions unlock downloads and future updates. Files already downloaded stay with the customer.</div>}</section>
      <section className="panel sales-panel"><div className="sales-panel-heading"><span className="step-number">02</span><div><h3>Your deal</h3><p>One clear offer. No surprise charges or stacking.</p></div></div><fieldset disabled={c.billing!=="once"}><label>Deal type<Choice label="Deal type" value={d.type} options={dealTypes.map(t=>[t,dealNames[t]])} onChange={v=>update({deal:{...d,type:v as Commerce["deal"]["type"]}})}/></label>{d.type!=="none"&&<div className="form-stack offer-fields">{!["bogo","bonus"].includes(d.type)&&<label>{d.type==="bundle"?"Bundle price · USD":d.type==="fixed"?"Discount · USD":"Discount · %"}<input type="number" min={0} max={["fixed","bundle"].includes(d.type)?9999:100} step="0.01" value={d.value} onChange={e=>update({deal:{...d,value:Number(e.target.value)}})}/></label>}{["bogo","bonus","bundle"].includes(d.type)&&<label>{d.type==="bundle"?"Second product in the bundle":"Product included free"}<Choice label="Included product" value={d.productId||"none"} options={references} onChange={v=>update({deal:{...d,productId:v==="none"?"":v}})}/><small>Digital BOGO includes a second, distinct product.</small></label>}{d.type==="volume"&&<label>Minimum licenses<input type="number" min={2} max={100} value={d.minimum} onChange={e=>update({deal:{...d,minimum:Number(e.target.value)}})}/><small>The discount applies to all licenses once this quantity is reached.</small></label>}<label>Promotion code <span className="optional">Optional</span><input placeholder="LAUNCH20" maxLength={30} value={d.code} onChange={e=>update({deal:{...d,code:e.target.value.toUpperCase()}})}/><small>Leave blank to apply automatically.</small></label><div className="form-two"><label>Starts <span className="optional">Optional</span><input type="datetime-local" value={localDate(d.startsAt)} onChange={e=>update({deal:{...d,startsAt:e.target.value?new Date(e.target.value).toISOString():""}})}/></label><label>Ends {!["early_bird","flash_sale"].includes(d.type)&&<span className="optional">Optional</span>}<input type="datetime-local" value={localDate(d.endsAt)} onChange={e=>update({deal:{...d,endsAt:e.target.value?new Date(e.target.value).toISOString():""}})}/></label></div></div>}</fieldset>{c.billing!=="once"&&<p className="sales-note">Deals are available for one-time purchases.</p>}</section>
      <section className="panel sales-panel"><div className="sales-panel-heading"><span className="step-number">03</span><div><h3>An optional upsell</h3><p>A useful add-on customers choose before checkout.</p></div><Switch aria-label="Enable checkout upsell" checked={c.upsell.enabled} disabled={c.billing!=="once"} onCheckedChange={v=>update({upsell:{...c.upsell,enabled:v}})}/></div>{c.upsell.enabled?<div className="form-stack"><label>Add-on product<Choice label="Upsell product" value={c.upsell.productId||"none"} options={references} onChange={v=>update({upsell:{...c.upsell,productId:v==="none"?"":v}})}/></label><div className="form-two"><label>Offer price · USD<input type="number" min={0} max={9999} step="0.01" value={c.upsell.price} onChange={e=>update({upsell:{...c.upsell,price:Number(e.target.value)}})}/></label><label>Headline<input maxLength={120} value={c.upsell.headline} onChange={e=>update({upsell:{...c.upsell,headline:e.target.value}})}/></label></div><label>Why it’s useful<textarea maxLength={400} value={c.upsell.description} onChange={e=>update({upsell:{...c.upsell,description:e.target.value}})}/></label></div>:<p className="sales-note">Offer a complementary product at a special price. Customers opt in; the add-on is never selected automatically.</p>}</section>
      <aside className="sales-note">FiveGen deals and subscriptions use Stripe. Your plan’s commission is collected automatically. Save your changes before sharing.</aside></div>
    :<div className="funnel-editor"><section className="panel sales-panel funnel-setup"><div className="sales-panel-heading"><div><h3>Your page. Your story.</h3><p>Arrange sections, write your copy, and shape the look.</p></div><Switch aria-label="Enable custom funnel" checked={f.enabled} onCheckedChange={v=>funnel({enabled:v,blocks:f.blocks.length?f.blocks:initialBlocks(product.title,product.description,product.content.benefits)})}/></div><div className="funnel-link"><code>/f/{product.slug}</code><button className="icon-button" aria-label="Copy funnel link" disabled={!f.enabled||product.status!=="published"} onClick={()=>void navigator.clipboard.writeText(`${location.origin}/f/${product.slug}`).then(()=>toast.success("Funnel link copied")).catch(()=>toast.error("Could not copy this link"))}><Copy size={16}/></button>{f.enabled&&product.status==="published"&&<a className="text-link" href={`/f/${product.slug}`} target="_blank" rel="noreferrer">Open saved page <ArrowUpRight size={14}/></a>}<button className="button secondary" disabled={!f.blocks.length} onClick={()=>setPreview(true)}><Eye size={16}/>Preview edits</button></div><p className="field-help">Save and publish your product to make its funnel available. The standard product page stays available too.</p></section>
      <div className="funnel-builder-grid"><section className="panel sales-panel"><h3>Page style</h3><div className="color-fields">{([["accent","Accent"],["background","Background"],["foreground","Text"]] as const).map(([key,label])=><label key={key}>{label}<input type="color" value={f[key]} onChange={e=>funnel({[key]:e.target.value})}/></label>)}</div><div className="form-stack"><label>Typography<Choice label="Funnel typography" value={f.font} options={[["sans","Modern sans"],["serif","Editorial serif"]]} onChange={v=>funnel({font:v as "sans"|"serif"})}/></label><label>Page width<Choice label="Funnel width" value={f.width} options={[["focused","Focused"],["wide","Wide"]]} onChange={v=>funnel({width:v as "focused"|"wide"})}/></label><label>Corners<Choice label="Funnel corners" value={f.radius} options={[["sharp","Sharp"],["soft","Soft"],["round","Round"]]} onChange={v=>funnel({radius:v as Commerce["funnel"]["radius"]})}/></label><label>Button label<input maxLength={50} value={f.cta} onChange={e=>funnel({cta:e.target.value})}/></label></div><div className="block-list-heading"><h3>Sections</h3><Choice label="Add funnel section" value="add" options={[["add","Add section…"],...["hero","text","benefits","image","video","testimonial","faq","offer"].map(k=>[k,k==="offer"?"Checkout":k.charAt(0).toUpperCase()+k.slice(1)] as [string,string])]} onChange={v=>{if(v==="add"||f.blocks.length>=20)return;const b:FunnelBlock={id:crypto.randomUUID(),kind:v as FunnelBlock["kind"],title:v==="offer"?"Get your copy":"Your heading",body:"",image:"",visible:true,align:"left"};funnel({blocks:[...f.blocks,b]});setSelected(f.blocks.length);}}/></div><ol className="funnel-block-list">{f.blocks.map((b,i)=><li key={b.id} className={selected===i?"selected":""}><button onClick={()=>setSelected(i)}><span>{String(i+1).padStart(2,"0")}</span><strong>{b.title||b.kind}</strong>{!b.visible&&<EyeOff size={13}/>}</button><button className="icon-button" disabled={i===0} aria-label={`Move ${b.title} up`} onClick={()=>{const blocks=[...f.blocks];[blocks[i-1],blocks[i]]=[blocks[i],blocks[i-1]];funnel({blocks});setSelected(i-1);}}><ArrowUp size={14}/></button><button className="icon-button" disabled={i===f.blocks.length-1} aria-label={`Move ${b.title} down`} onClick={()=>{const blocks=[...f.blocks];[blocks[i],blocks[i+1]]=[blocks[i+1],blocks[i]];funnel({blocks});setSelected(i+1);}}><ArrowDown size={14}/></button></li>)}</ol></section>
      <section className="panel sales-panel block-settings">{f.blocks[selected]?<><div className="sales-panel-heading"><div><span className="eyebrow">{f.blocks[selected].kind.toUpperCase()} SECTION</span><h3>Edit your section</h3></div><Switch aria-label="Section visible" checked={f.blocks[selected].visible} onCheckedChange={visible=>setBlock({visible})}/></div><div className="form-stack"><label>Heading<input maxLength={160} value={f.blocks[selected].title} onChange={e=>setBlock({title:e.target.value})}/></label><label>{f.blocks[selected].kind==="faq"?"Questions & answers":f.blocks[selected].kind==="benefits"?"Benefits · one per line":"Content"}<textarea rows={7} maxLength={8000} value={f.blocks[selected].body} onChange={e=>setBlock({body:e.target.value})}/><small>{f.blocks[selected].kind==="faq"?"One question per line: Question | Answer":f.blocks[selected].kind==="testimonial"?"Use a real customer’s quote with their permission.":"Your copy appears exactly as written."}</small></label>{["hero","image","video"].includes(f.blocks[selected].kind)&&<label>{f.blocks[selected].kind==="video"?"Video URL · MP4 or WebM":"Image URL"}<input type="url" placeholder="https://…" value={f.blocks[selected].image} onChange={e=>setBlock({image:e.target.value})}/></label>}<label>Alignment<Choice label="Section alignment" value={f.blocks[selected].align} options={[["left","Left"],["center","Center"]]} onChange={v=>setBlock({align:v as "left"|"center"})}/></label><button className="button secondary" onClick={()=>{funnel({blocks:f.blocks.filter((_,i)=>i!==selected)});setSelected(Math.max(0,selected-1));}}><Trash2 size={15}/>Remove section</button></div></>:<div className="funnel-empty"><WandSparkles size={28}/><h3>Start with your story</h3><p>Add a section, or use a starting layout.</p><button className="button primary" onClick={()=>{funnel({blocks:initialBlocks(product.title,product.description,product.content.benefits)});setSelected(0);}}>Use starter layout</button></div>}</section></div></div>}
    {!errors.success&&<p className="error-banner" role="status">{errors.error.issues[0].message}</p>}
    <Dialog open={preview} onOpenChange={setPreview}><DialogContent className="flow-dialog funnel-preview-dialog"><div className="flow-header"><DialogTitle>Funnel preview</DialogTitle><DialogDescription>Your current edits. Save and publish when you’re ready.</DialogDescription></div><div className="flow-body"><FunnelView funnel={f} preview checkout={<div><strong className="funnel-preview-price">{money(product.price*100)}{c.billing!=="once"&&`/${c.billing}`}</strong><p>Offer and add-ons are calculated at checkout.</p><button className="funnel-cta" onClick={()=>setPreview(false)}>{f.cta}</button><small>Preview only</small></div>}/></div><footer className="flow-footer"><button className="button primary" onClick={()=>setPreview(false)}>Back to editing</button></footer></DialogContent></Dialog>
  </div>;
}
function localDate(value:string){if(!value)return "";const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
