'use client';
import {useState} from 'react';
import {ArrowRight,Check,Loader2,Sparkles} from 'lucide-react';
import {Brand} from '../ui-brand';
// Kept separate from server helpers so no database code enters the browser.
const version='2026-09-11-credits';
export function TermsConsent({email,returnTo}:{email:string;returnTo:string}){
 const [accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <main className="consent-page"><a href="/" className="consent-brand"><Brand/></a><section className="consent-card"><div className="consent-symbol"><Sparkles size={26}/></div><span className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</span><h1>One workspace.<br/>Every possibility.</h1><p className="consent-intro">Build, launch, and grow with every FiveGen tool included.</p><ul className="consent-benefits">{['Unlimited manual products, funnels, and deals','Courses, communities, bookings, and partners','3 complete AI products included each month','Buy credits for more AI products, images, and videos'].map(t=><li key={t}><Check size={16}/>{t}</li>)}</ul><form onSubmit={async e=>{e.preventDefault();if(!accepted)return;setBusy(true);setError('');try{const r=await fetch('/api/terms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accepted:true,version})});if(!r.ok)throw new Error(((await r.json()) as any).error);location.assign(returnTo);}catch(e){setError((e as Error).message);setBusy(false);}}}><label className="terms-checkbox"><input type="checkbox" required checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I agree to the <a href="/terms" target="_blank" rel="noreferrer">Terms & Conditions</a>, including the <a href="/terms#selling-fees" target="_blank" rel="noreferrer">selling fees and payment terms</a>.</span></label>{error&&<p className="error-banner" role="alert">{error}</p>}<button className="button primary full" disabled={!accepted||busy}>{busy?<Loader2 size={18} className="spin"/>:<ArrowRight size={18}/>} {busy?'Opening your workspace…':'Enter my workspace'}</button></form><small className="consent-account">Signed in as {email} · <a href="/signout-with-chatgpt">Switch account</a></small></section></main>;
}
