import type { Brief } from "./product";

export const productRecipes = {
  Guide: { label: "Guide & ebook", unit: "Chapter", description: "A clear explanation, worked examples, and a practical workbook.", outcome: "What should readers be able to do after finishing?", example: "Help first-time freelancers write a scoped proposal and price a first project.", deliverables: ["Readable ebook", "Worked examples", "Action workbook"], architecture: "Build a logical reader journey from a specific problem to an achievable outcome. Each chapter teaches one distinct idea, with original worked examples and exercises. Deliver a printable workbook.md and an action-checklist.md." },
  "Mini course": { label: "Course", unit: "Lesson", description: "Downloadable lessons, instructor scripts, practice and assessment.", outcome: "What skill will students practice and demonstrate?", example: "Teach food photographers to style, light, shoot, and edit one portfolio-ready image.", deliverables: ["Lesson curriculum", "Instructor scripts", "Practice & assessment"], architecture: "Use the requested lesson count, or 4–8 when unspecified, with observable learning objectives, concise teaching content, a demonstration, a practice assignment, and an assessment with answers. Each body is learner-facing lesson notes; provide a separate instructor-video-scripts.md and assessment.md. Never claim a video was recorded. This is a private downloadable course kit, not a hosted classroom. Optional short promotional videos are generated separately using credits." },
  "Template kit": { label: "Template kit", unit: "Tool", description: "Ready-to-use templates and files, with a quick-start guide.", outcome: "What repetitive task should these templates make easier?", example: "Give a two-person design studio a client brief, scope calculator, and handoff checklist.", deliverables: ["Editable templates", "Completed examples", "Quick-start instructions"], architecture: "Organize sections around 3–6 usable tools rather than essay chapters. For each explain when to use it, the fields to fill in, and a worked example. The final files MUST contain the actual editable templates, not descriptions of templates. Use CSV, Markdown, JSON or self-contained HTML as appropriate. Include both a clean template and a clearly labelled example. Never claim native Notion or Excel support from a Markdown or CSV file." },
  Challenge: { label: "Challenge", unit: "Day", description: "A daily action plan with exercises, checkpoints, and a tracker.", outcome: "What change will participants work toward each day?", example: "Help camera-shy founders publish seven useful talking-head videos in seven days.", deliverables: ["Daily activities", "Progress tracker", "Reflection prompts"], architecture: "Create exactly the requested number of days (default 7, maximum 30). Every day has a different concrete activity, time estimate, completion criterion and reflection question. Increase difficulty sensibly. Include a daily-tracker.csv and a review-workbook.md. Avoid repeating the same task under different titles." },
  Playbook: { label: "Playbook", unit: "Process", description: "Repeatable processes, decision rules, and operational checklists.", outcome: "What process will someone repeat successfully?", example: "Help a small agency run a weekly client reporting process in under an hour.", deliverables: ["Step-by-step SOPs", "Decision checklists", "Reusable operating tools"], architecture: "Create an operating system of distinct procedures. Each procedure states its trigger, owner, inputs, ordered steps, decision branches, definition of done and failure recovery. Include editable SOP and checklist files. Use a realistic running example specific to the brief." },
  "Custom product": { label: "Custom product", unit: "Component", description: "Calculators, code kits, worksheets, and other useful resources.", outcome: "What exactly should the finished product contain and do?", example: "Build an offline HTML pricing calculator for handmade ceramics, plus a cost worksheet.", deliverables: ["Purpose-built deliverables", "Usage instructions", "Supporting resources"], architecture: "Choose deliverables that implement the requested functionality. For a calculator deliver a complete offline HTML/CSS/JS file; for a code kit deliver complete source and setup instructions; for a worksheet deliver a usable structured file. Documentation supports the main artifact and never substitutes for it. No network calls, secrets, fake integrations, or nonfunctional buttons in generated tools." },
  "Coaching session": { label: "Coaching & meetings", unit: "Resource", description: "A bookable session with preparation, scheduling, and follow-up.", outcome: "What will the customer leave the meeting with?", example: "Offer a 45-minute portfolio review with a prioritized improvement plan for junior designers.", deliverables: ["Session agenda", "Booking & preparation", "Follow-up workbook"], architecture: "Create a service package with a precise scope, a session agenda, preparation questions and a follow-up action worksheet. Make clear that a human creator delivers the meeting. Do not invent credentials or claim meetings have happened. Include intake-questions.md and session-workbook.md." },
  Community: { label: "Community", unit: "Resource", description: "A private member space with discussions and shared resources.", outcome: "Why will members return and help each other?", example: "Create a private practice community for freelance illustrators sharing weekly portfolio critiques.", deliverables: ["Member onboarding", "Private discussions", "Resource library"], architecture: "Build a community launch package: member promise and scope, onboarding, respectful discussion rules, a weekly participation rhythm and useful member resources. Write prompts as suggestions for the host, never as fake member posts or testimonials. Include community-guidelines.md and a host-calendar.csv." },
} as const;

export function recipeFor(format: Brief["format"]) { return productRecipes[format] || productRecipes["Custom product"]; }
export function generationDirection(brief: Brief, id: string) {
  return `Follow the explicitly agreed scope and unit count in the creator brief before these format defaults. Supporting files are separate resources, not extra chapters or lessons. ${recipeFor(brief.format).architecture}\nCreator's differentiating angle: ${brief.angle || "Develop a specific approach grounded in this audience and outcome; avoid generic advice."}\nProject creative seed: ${id}. Use a distinctive structure, named examples and visual direction for THIS brief. Do not repeat stock examples or claim guaranteed earnings. Challenge duration: ${brief.duration || 7} days. Language: ${brief.language || "English"}.`;
}
