import { z } from "zod";
import { ApiError,database,failure,identity,sameOrigin } from "@/lib/server";
import { cancelBooking } from "@/lib/customer-journey";
export async function GET(req:Request){try{
 const u=await identity(),db=database(),days=Math.min(365,Math.max(1,Number(new URL(req.url).searchParams.get('days'))||30)),after=Date.now()-days*86400000;
 const [leads,bookings,sales,counts]=await Promise.all([
 db.prepare("SELECT l.*,p.title,(SELECT COUNT(*) FROM orders o WHERE o.owner=l.owner AND lower(o.email)=l.email AND o.provider<>'free') purchases FROM leads l JOIN products p ON p.id=l.product_id WHERE l.owner=? AND l.created_at>=? ORDER BY l.created_at DESC LIMIT 1000").bind(u.userId,after).all(),
 db.prepare("SELECT b.*,s.starts_at,s.duration,p.title FROM bookings b JOIN booking_slots s ON s.id=b.slot_id JOIN products p ON p.id=b.product_id WHERE b.owner=? AND s.starts_at>=? ORDER BY s.starts_at DESC LIMIT 1000").bind(u.userId,after).all(),
 db.prepare("SELECT o.id,o.email,o.amount,o.platform_fee,o.created_at,p.title,COALESCE(c.amount,0) referral_fee FROM orders o JOIN products p ON p.id=o.product_id LEFT JOIN referral_commissions c ON c.order_id=o.id AND c.state NOT IN ('void','reversed') WHERE o.owner=? AND o.provider<>'free' AND o.created_at>=? ORDER BY o.created_at DESC LIMIT 1000").bind(u.userId,after).all(),
 db.prepare("SELECT (SELECT COUNT(*) FROM leads WHERE owner=? AND created_at>=?) leads,(SELECT COUNT(*) FROM leads l WHERE l.owner=? AND l.created_at>=? AND EXISTS(SELECT 1 FROM bookings b WHERE b.product_id=l.product_id AND b.email=l.email AND b.status<>'cancelled')) booked_leads,(SELECT COUNT(*) FROM bookings b JOIN booking_slots s ON s.id=b.slot_id WHERE b.owner=? AND s.starts_at>=? AND b.status='attended') attended,(SELECT COUNT(*) FROM bookings b JOIN booking_slots s ON s.id=b.slot_id WHERE b.owner=? AND s.starts_at>=? AND b.status='no_show') no_shows,(SELECT COUNT(*) FROM orders WHERE owner=? AND provider<>'free' AND created_at>=?) sales,(SELECT COALESCE(SUM(amount),0) FROM orders WHERE owner=? AND provider<>'free' AND created_at>=?) revenue").bind(u.userId,after,u.userId,after,u.userId,after,u.userId,after,u.userId,after,u.userId,after).first(),
 ]);
 return Response.json({leads:leads.results,bookings:bookings.results,sales:sales.results,counts,days,limit:1000},{headers:{"Cache-Control":"private, no-store"}});
}catch(e){return failure(e);}}
export async function PATCH(req:Request){try{sameOrigin(req);const u=await identity(),d=z.object({id:z.string().uuid(),status:z.enum(['attended','no_show','confirmed','cancelled'])}).parse(await req.json());const b=await database().prepare("SELECT b.*,s.starts_at FROM bookings b JOIN booking_slots s ON s.id=b.slot_id WHERE b.id=? AND b.owner=?").bind(d.id,u.userId).first();if(!b)throw new ApiError("Booking not found.",404);if(d.status==='cancelled')await cancelBooking(d.id,u.userId);else{if(b.status==='cancelled')throw new ApiError("A cancelled booking cannot be reopened. Create a new booking.",409);if(d.status!=='confirmed'&&Number(b.starts_at)>Date.now())throw new ApiError("Record attendance after the scheduled start time.",409);await database().prepare("UPDATE bookings SET status=? WHERE id=? AND owner=?").bind(d.status,d.id,u.userId).run();}return Response.json({saved:true});}catch(e){return failure(e);}}
